vendor_id=0x0403
product_id=0x6001

self_powered=false
remote_wakeup=true
use_serial=true
max_power=90

manufacturer="FTDI"
product="FT232R USB UART"
serial="A5069RR4"

filename="/home/ubuntu/Projects/MYSELF/ZTE/tools/ft232_backup.bin"
