// SPDX-License-Identifier: GPL-2.0
/*
 * ZTE ZXIC ZX279128S — integrated Ethernet driver.
 *
 * The SoC integrates an on-chip 4-port switch fed by four built-in
 * gigabit PHYs (driver: drivers/net/phy/phy-zte-gephy.c, talked to via
 * drivers/net/mdio/mdio-zte.c) and a packet processor pipeline that
 * delivers frames to the host through an IDM DMA ring:
 *
 *   RJ45 → GePHY → MAC[0..3] → on-chip switch (SW)
 *                            → packet processor (PP)
 *                            → DDR via PP_AXI / IDM ring
 *
 * This driver currently owns the whole pipeline as a single platform
 * driver. A future DSA split would expose 4 user-port netdevs + one
 * CPU-conduit; until then `eth0` is the CPU port (named "sw") and
 * `idm0`/`idm1` are the two wifi-offload conduits.
 *
 * MMIO map driven from DT (compatible "zte,zx279128s-eth"):
 *   reg[pon] : 0x92000000 + 0x1c0000   PON-side regs (CLA, FDB, …)
 *   reg[npp] : 0x921c0000 + 0x200000   NPP/IDM/TM/PP unified window
 *     +0x008000  IDM (descriptor rings, IRQ, RX/TX kick)
 *     +0x040000  MAC0..3                ← user ports
 *     +0x140000  MAC4 (RGMII WAN — unused on H3600)
 *     +0x180000  TM   (Traffic Manager)
 *     +0x1c0000  PP   (Packet Processor)
 *   syscon  : zte,topcrm phandle        clock-mux for PON-side blocks
 *
 * Most of the bring-up is bit-exact replay of what stock's
 * plat-zxylzb_9128S.ko / tm.ko produce at boot, captured into static
 * tables (zx_stock_*.h, zx_cla_table.h, zx_pm_table.h, zx_npp_twin_data.h).
 * Some sub-blocks of that replay are now explicit named init functions;
 * the remainder go through a generic per-block apply walker.
 */

#include <linux/delay.h>
#include <linux/dma-mapping.h>
#include <linux/etherdevice.h>
#include <linux/interrupt.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/mii.h>
#include <linux/of.h>
#include <linux/of_address.h>
#include <linux/of_mdio.h>
#include <linux/phy.h>
#include <linux/platform_device.h>
#include <linux/skbuff.h>
#include <linux/ip.h>
#include <linux/tcp.h>	/* [Stage-3 UP offload 2026-07-28] TCP-data-only
			 * injection filter in zx_wifi_rx_handler */
#include <net/checksum.h>	/* [Phase C 2026-07-28] ip_fast_csum for the DN
				 * WiFi-dispatch IP-checksum repair */
#include <linux/spinlock.h>
#include <linux/mutex.h>
#include <linux/notifier.h>	/* [WiFi auto-bind] netdevice notifier */

#include <asm/cacheflush.h>

#include <linux/debugfs.h>
#include <linux/seq_file.h>
#include <linux/dsa/zte.h>
#include <linux/list.h>
#include <linux/rtnetlink.h>
#include <net/dsa.h>
#include <net/net_namespace.h>	/* [Stage-3 WiFi Phase B] init_net for dev_get_by_name */
#include <net/flow_offload.h>
#include <net/neighbour.h>
#include <net/route.h>
#include <net/pkt_cls.h>

/* Descriptor tables decoded from stock tm.ko's *RegTable symbols
 * (zx-fpga-reg-tables.h) and an older curated subset (zx_reg_tables.h);
 * used by the descriptor-driven access path (zx_fpga_table_write).
 */
#include "zx-pon-plat.h"
#include "zx_reg_tables.h"
#include "zx-fpga-reg-tables.h"
#include "zx-pp-pro-actions.h"

/* Static replay tables — captured from stock, regenerated by scripts
 * in tasks/00.01.eth-driver/scripts/.
 */
#include "zx_stock_bursts.h"
#include "zx_npp_twin_data.h"

/* CLA RAM-7 (CPU-queue assignment) address range — used by
 * zx_cla_apply_replay to generate the constant-payload entries that
 * sit alongside the snapshot-captured ones.
 */
#define ZX_CLA_RAM7_FIRST  0
#define ZX_CLA_RAM7_LAST   1023

#define DRV_NAME "zx279128-eth"

/* ---------- NPP / IDM register map (npp_base) ---------- */
#define NPP_REG_MASK_GLOBAL	0x0004
#define NPP_REG_IRQ_ENABLE	0x0008
#define NPP_REG_IRQ_MASK	0x000C
#define NPP_REG_CONTROL		0x0040
#define NPP_REG_RESET		0x0048
#define NPP_REG_SIPC_INIT	0xC000
#define NPP_REG_SMCT_INIT_0	0x10000
#define NPP_REG_SMCT_PP_PMAU	0x10004	/* SMCT pp_pmau credit pools (phys 0x921d0004) */
#define NPP_REG_SMCT_INIT_1	0x10010
#define NPP_REG_INIT_VAL	0x10008
#define NPP_REG_SPA_INIT	0x141C0
#define NPP_REG_UOPC_INIT	0x18000
/* SOPC↔SMAC bridge glue (see zx_eth_adjust_link / zx_mac_keepalive_fn):
 * 0x19068 bit(port+5) = transient READY (poll), bit(port) = bridge ENABLE;
 * 0x19038 bit(port+16) = half-duplex flag. */
#define NPP_REG_SOPC_BRIDGE	0x19068
#define NPP_REG_SOPC_DUPLEX	0x19038

/* IDM regs (still within npp_base, offset +0x8000) */
#define IDM_REG_CONTROL		0x8000
/* Stock writes idm_desc_addr (offset 0 = RX descs) to npp+0x8008 and
 * idm_desc_addr+0x4000 (TX descs) to npp+0x8004. Our defines were SWAPPED:
 * Fixed via RE of pon_npp_idm_init.
 */
#define IDM_REG_TX_DESC_BASE	0x8004
#define IDM_REG_RX_DESC_BASE	0x8008
#define IDM_REG_RX_ENABLE	0x800C
#define IDM_REG_REG_10		0x8010
#define IDM_REG_REG_18		0x8018
#define IDM_REG_TIMEOUT		0x801C
#define IDM_REG_IRQ_STATUS	0x8020
#define IDM_REG_IRQ_MASK	0x8024
#define IDM_REG_TX_KICK		0x8040
#define IDM_REG_TX_STATUS	0x8044
#define IDM_REG_RX_KICK		0x8048
#define IDM_REG_RX_QLEN		0x804C
#define IDM_REG_REG_C0		0x80C0

/* PP (Packet Processor — routes SW frames to CPU via NPP/IDM rings) */
#define PP_OFF			0x1C0000
#define PP_REG_CTRL_0		0x0000
#define PP_REG_CTRL_28		0x0028
#define PP_REG_CPU_FWD		0x002C
/* Bridge / classifier sub-block at PP_OFF + 0x8000 / +0xC000 */
#define PP_BRG_BASE		0x8000
#define PP_CLA_BASE		0xC000

/* TOP_CRM clock control: base address comes from the zte,topcrm phandle,
 * mapped separately from the main NPP block. The two offsets we touch are
 * verified against the stock zx_pon_clk_reset_init sequence.
 */
#define TOPCRM_REG_PON_CLK	0x0C	/* zx_pon_clk_reset_init final write: |= 0x1E0 */
#define TOPCRM_PON_CLK_BITS	0x1E0	/* bits 5-8 — PON subsystem clocks */

/* CPU forwarding bit: stock does pp[0x2c] |= 1 << (lan_up_port + 0x19).
 * lan_up_port = 0 for LAN-only mode (g_pon_work_mode==0x10) → bit 25.
 */
#define PP_CPU_FWD_BIT		BIT(25)

/* ===== TM (Traffic Manager) — CPU↔switch path (the REAL one for ethernet) ===== */
#define TM_OFF			0x180000	/* npp_base + 0x180000 = 0x92340000 */
#define TM_INSTANCE_STRIDE	0x400	/* TM has 4 schedulers + 5 BMU instances at this stride */
#define TM_NUM_INSTANCES	4	/* used by zx_tm_pre_init / zx_tm_post_bmu */
#define TM_REG_BPPE_BASE	0x00E8	/* global TM BPPE physical addr in DDR */
#define TM_REG_JUMBO_BPPE_BASE	0x00EC	/* global TM Jumbo BPPE */
#define TM_REG_BP_BUFFER_BASE	0x00F4	/* global TM BP buffer */
#define TM_REG_BP_JUMBO_BASE	0x00F8	/* global TM Jumbo BP buffer */
#define TM_REG_BP_SIZE		0x00FC	/* global TM: low 16=BP_SIZE, high 16=JUMBO_BP_SIZE */
#define TM_REG_IRQ_MASK		0x0104
#define TM_REG_BMU_INIT		0x8000
#define TM_REG_BMU_CTRL		0x8004
#define TM_REG_BMU_CTRL2	0x8008
#define TM_REG_BMU_ALLOC_RESULT	0x800C
#define TM_REG_BMU_FREE		0x8010	/* write bp_idx -> return BP to free pool */
#define TM_REG_BMU_ALLOC_CTRL	0x8014
#define TM_REG_BMU_POOL_SIZE	0x8048	/* high 16 = BPPE_POOL_SIZE */
#define TM_REG_BMU_JUMBO_POOL	0x804C
#define TM_REG_BMU_BUCKETS_M1	0x8058	/* (POOL_SIZE>>5)-1 */
#define TM_REG_BMU_JUMBO_BUCK	0x805C
#define TM_REG_DMA_CTRL		0x10000
#define TM_REG_DMA_REG20	0x10020
#define TM_REG_DMA_REG24	0x10024
#define TM_REG_DMA_REG28	0x10028
#define TM_REG_DMA_REG2C	0x1002C
#define TM_REG_DMA_TIMEOUT	0x10030
#define TM_REG_DMA_REG34	0x10034
#define TM_REG_DMA_REG3C	0x1003C
#define TM_REG_DMA_TX_UP_BASE	0x10050
#define TM_REG_DMA_DESC_CNT_UP	0x10058
#define TM_REG_DMA_TX_DN_BASE	0x10060
#define TM_REG_DMA_DESC_CNT_DN	0x10068
#define TM_REG_DMA_REG388	0x10388
#define TM_REG_DMA_TX_UP_KICK	0x10054	/* write 1 = kick the UP (CPU-TX) DMA queue */
#define TM_REG_BMU_BP_STAT	0x80DC	/* bits 8:3 = allow_free_cnt refill (see zx_sw_xmit) */

/* RED congestion block, TM-RELATIVE offsets (tm_read/tm_write land at phys
 * 0x92344xxx = the real RED block; contrast the RED_OFF/NPP-relative defines
 * at zx_red_block_init which are the documented dead-space latent bug).
 * DATASHEET.md: RED base 0x92344000. */
#define TM_RED_CFG		0x4004	/* phys 0x92344004; reset/stock value 0xDE */
#define TM_RED_CFG_CPUDN_CHARGE	0x40u	/* bit6 = cpuDn out-buffer charge-accounting —
					 * MUST stay CLEARED on mainline (churn/WAN-RX
					 * 1024-wedge root cause, [red-arm 2026-07-04]) */
#define TM_RED_QCFG_CMD		0x4014	/* q_idx | (type<<22) commits the 4 cfg words */
#define TM_RED_QCFG_READY	0x4018	/* poll bit0 == 1 before commit */
#define TM_RED_QCFG_DATA0	0x401C
#define TM_RED_QCFG_DATA1	0x4020
#define TM_RED_QCFG_DATA2	0x4024
#define TM_RED_QCFG_DATA3	0x4028
#define TM_RED_PORT_MASK	0x4040	/* RX port/queue gating mask (stock dump 0x3ff) */
#define TM_RED_RELEASE_GO	0x4064	/* write 1 = commit release; poll bit0 busy */
#define TM_RED_RELEASE		0x4068	/* (ring<<14) | (count<<4) | (sop<<3) | qid */
#define TM_RED_OUT_SHARE_MAX	0x4074	/* stock dump 0x3fff */

/* QMG queue-manager threshold, TM-relative (phys 0x9234c000):
 * [12:0] = up_ram_thd, [25:13] = dn_ram_thd (DATASHEET.md). */
#define TM_QMG_THD		0xC000

#define TM_RX_QCNT_BASE		(0x4040 * 4)	/* tm[0x10100+q*4] per-queue RX count */
/* TM IRQ_MASK semantics: 1 = MASKED. Stock unmasks bits 0 (RX) and 1 (TX).
 *
 * We currently unmask bit 0 only. The NAPI poll handles RX queues by reading
 * per-queue counters and releasing RX descs, which clears the bit 0 IRQ
 * source. We do not yet implement TX-completion reclaim (TX done is observed
 * via tm_tx_count counter rather than per-frame), so leaving bit 1 unmasked
 * causes an IRQ storm — HW asserts bit 1 after the first TX, the handler
 * runs, NAPI finds no RX work and re-arms, the bit is still asserted, IRQ
 * refires immediately.
 *
 * Masking bit 1 entirely is a known-safe stop-gap pending proper TX-completion
 * reclaim. See tasks/00.01.eth-driver/findings/ping_bidi_irq_storm_2026-05-27.md.
 */
#define TM_IRQ_ARM_BITS		0x03		/* bits 0+1 — RX (0) + TX done (1), stock match (after carved+SOPC+TM[0xc000] fixes, the storm from Iter 13 should not recur) */

/* Stock prints `BPPE_POOL_SIZE=2000` in `pon init` = 0x2000 = 8192. Match
 * stock to avoid buffer exhaustion under sustained traffic (boot UART capture, mainline_eth/captures/boot_init.log).
 */
#define TM_BPPE_POOL_SIZE	8192	/* = stock 0x2000. Restored 2026-06-04 (Iter S): the
					 * earlier 1024 was to dodge an 18MB dma_alloc_coherent
					 * CMA failure, but pools are now carved from the reserved
					 * region via memremap_wc (zx_tm_alloc_pools), so that
					 * reason is moot. 8192 × TM_BP_SIZE(2304) = 18 MiB fits the
					 * BP region (CARVED_BP_OFF 0x2C20000 → RXDESC 0x3F1F000 =
					 * ~20 MiB). ROOT CAUSE of the unicast→CPU wedge: the 1024
					 * BP pool exhausts after ~1024 trapped frames (tm_rx_count
					 * latched at ~1033-1048 every run) → HW can't receive → wedge.
					 */
#define TM_BP_SIZE		2304	/* stock has 0x900=2304 (NOT 2048!) in TM[0xFC] low16 */
#define TM_TX_RING_SIZE		1024
#define TM_TX_DESC_SIZE		16
#define TM_JUMBO_BP_SIZE	10240	/* stock high16 of TM[0xFC] = 0x2800=10240 */
#define TM_JUMBO_BPPE_POOL_SIZE	0x66	/* stock jumbo pool = 102 entries */
#define TM_NUM_RX_QUEUES	8
#define TM_RX_DESC_PER_Q	1024	/* Stock uses idx % 0x400 (1024); was 256 — explains why we saw zeros */
#define TM_DESC_SIZE		16

/* BRG (Bridge) sub-block of PP — indirect RAM access registers + FDB hash. */
#define PP_BRG_RAM_CMD		0x8014	/* bucket | (slot<<22) | (0x08000000=read) */
#define PP_BRG_RAM_READY	0x8018	/* poll bit 0 == 1 before issuing */
#define PP_BRG_RAM_D0		0x801C	/* data word 0 */
#define PP_BRG_RAM_D1		0x8020	/* data word 1 */
#define PP_BRG_RAM_D2		0x8024	/* data word 2 */
#define PP_BRG_RAM_TABLE_SIZE	0x8184	/* low 2 bits index a mac_table_size[] of u16 */
#define PP_BRG_ISOLATE(p)	(0x83C0 + (p) * 4)	/* per-port isolation mask */
#define PP_BRG_PKTDEAL_FLOOD	0x8340	/* [15:0] pktdeal verdicts (2b/proto),
					 * [31:24] unknown-unicast fwd REGPORT bitmap
					 * (sbragRegTable[0x36], phys 0x92388340) */
#define PP_BRG_VLAN_BASE	0x8000	/* TODO: VLAN tables indirect addressed too */
#define BRG_RAM_READ		0x08000000

/* Port number assignments (inferred from stock pon_pp_brg_init):
 *  ports 0..3 = LAN MACs 0..3
 *  port  4    = MAC4 (RGMII WAN)
 *  port  5    = ?  (PON?)
 *  ports 6,7  = CPU/internal — stock isolates both with mask 0xdf
 * Use port 6 as our CPU port for idm0/idm1 FDB entries.
 */
#define ZX_CPU_PORT		5	/* Stock active CLA rule has inport=5 → CPU port is 5 (mined from stock /sys debug). */

/* MAC[i] window — base = npp_base + (i+1) * 0x40000 */
#define MAC_STRIDE		0x40000
#define MAC_REG_CONTROL		0x0000
#define MAC_REG_IRQ_MASK	0x0004
#define MAC_REG_ENABLE		0x0008
#define MAC_REG_PHY_CB		0x00E0
#define MAC_REG_D00		0x0D00
#define MAC_REG_D30		0x0D30

#define ZX_NUM_MACS		5	/* MAC0..3 = LAN GePHYs; MAC4 = WAN (external ZX5201 PHY @ MDIO 0x08, RGMII). WAN port bring-up: wan_port_bringup_re.md */

/* IRQ bits in IDM_REG_IRQ_STATUS / IRQ_MASK.
 * Per stock idm_net_int / idm_net_poll, masking semantics is unclear:
 *   - idm_net_init writes mask = idm_int_mask (zero-init global → 0)
 *   - idm_net_int does `mask |= 0x14` (set bits 2,4)
 *   - idm_net_poll does `mask &= ~0x14` (clear bits 2,4) on NAPI complete
 * The pattern "set in handler, clear in poll-complete" is consistent with
 * "1 = MASKED" semantics on bits 2 (RX) and 4 (TX). Bit 0 is unknown.
 */
#define IDM_IRQ_RX		0x04	/* bit 2 — RX pending */
#define IDM_IRQ_TX		0x10	/* bit 4 — TX done */
#define IDM_IRQ_NAPI_MASK	(IDM_IRQ_RX | IDM_IRQ_TX)
#define IDM_IRQ_ALL_MASKED	0x1F	/* mask everything */

/* Descriptor ring geometry (from RE) */
#define IDM_RX_RING_SIZE	2048
#define IDM_TX_RING_SIZE	1024
#define IDM_DESC_SIZE		8
#define IDM_RX_RING_BYTES	(IDM_RX_RING_SIZE * IDM_DESC_SIZE)	/* 16 KB */
#define IDM_TX_RING_BYTES	(IDM_TX_RING_SIZE * IDM_DESC_SIZE)	/* 8 KB */
#define IDM_DESC_BUF_BYTES	(IDM_RX_RING_BYTES + IDM_TX_RING_BYTES)	/* 24 KB */
#define IDM_TX_DESC_OFFSET	IDM_RX_RING_BYTES			/* TX after RX */

#define IDM_RX_SKB_SIZE		0x6C4		/* 1732 — matches stock alloc */
#define IDM_RX_SKB_HEADROOM	0x20		/* 32 B reserve */
#define IDM_TX_POOL_LIMIT	0x200
#define IDM_TX_PORT_LIMIT	0x400

/* Descriptor word [4:8] bit fields (TX) */
#define IDM_DESC_LEN_MASK	0x1FFFFF
/* [Stage-3 WiFi Phase B, 2026-07-23] TX-desc word1 bits 28..30 = ssid, bit 31
 * = ring select (IDM_DESC_PORT_BIT). Verified against stock idm_net_tx
 * (decomp_all_plat_zxylzb_9128S.c:4268-4270: desc[1] = len | ring<<31 |
 * cb[0xb7]<<28) — see findings/wifi_stage3_phaseB_dispatcher_spec_2026-07-07.md
 * §2.2. RENAMED from the old, unused-and-misnamed IDM_DESC_CSUM_SHIFT (which
 * was an early mis-transcription of exactly these ssid bits; do NOT re-add a
 * second define for bit 28). */
#define IDM_DESC_SSID_SHIFT	28
#define IDM_DESC_SSID_MASK	0x7
#define IDM_DESC_PORT_BIT	BIT(31)

#define ZX_NPORTS		2	/* idm0 + idm1 */

/* [Stage-3 WiFi Phase B, 2026-07-23] ssid carried in skb->cb from the WiFi
 * vif's rx_handler (zx_wifi_rx_handler) into zx_idm_xmit's TX-descriptor
 * packer. Stock uses skb->cb[0xb7], but that offset is out of bounds for
 * mainline's 48-byte sk_buff::cb — a fresh in-bounds offset is used here per
 * the spec's step-3 correction. The magic byte gates application so ordinary
 * (non-WiFi) traffic through zx_idm_xmit keeps today's behavior (no ssid bits
 * added) when no tag was stamped. UNTESTED ON HARDWARE — staged for later
 * hardware validation (spec §2.2/§2.3). */
struct zx_skb_wifi_tag {
	u8 magic;
	u8 ssid;
};
#define ZX_SKB_CB_TAG_OFF	40
#define ZX_SKB_CB_TAG_MAGIC	0x5a
/* [Stage-3 WiFi Phase B.2, 2026-07-24] "shuttled" marker: stamped on skbs the
 * TM trap-RX path delivers INTO a bound vif (zx_wifi_tm_rx_dispatch) so the
 * vif's zx_wifi_rx_handler passes them to the local stack instead of
 * re-injecting them into the fabric (infinite vif->ring->trap->vif loop
 * otherwise). cb is preserved across netif_rx()'s backlog. */
#define ZX_SKB_CB_TAG_MAGIC_SHUTTLED	0xa5

/* [Stage-3 WiFi Phase B, 2026-07-23] IDM ring <-> WiFi-vif dispatch node.
 * node_index = ssid + idm*8 (range 0..15, 2 rings × 8 ssid) — confirmed from
 * three independent stock sites (get_node_index.c:16, idm_fdb_forward.c:25,
 * idm_fdb_multi_send_handle.c:219). idm/ssid are position-determined constants
 * (mirrors stock's static fdb_list initializer). A mainline binding owns both
 * ends of the mapping, so this replaces stock's register_idm_fdb_node +
 * WlanIndex2WlanIdmMap indirection with a direct (idm,ssid)→vif table
 * (spec §1.3/§3). UNTESTED ON HARDWARE. */
struct zx_wifi_dispatch_node {
	bool enabled;
	u8 idm;				/* ring 0/1 (= node_index >> 3) */
	u8 ssid;			/* 0..7    (= node_index & 7)  */
	struct net_device *idm_ndev;	/* the idmN netdev (= ports[idm].netdev) */
	struct net_device *wlan_ndev;	/* the bound mac80211 vif netdev */
	/* [Stage-3 WiFi UP 2026-07-28] the vif's ifindex, cached at bind time so
	 * the FT install path can recognize a WiFi-INGRESS flow (nf_flow_table's
	 * FLOW_DISSECTOR_KEY_META ingress_ifindex) by integer compare — no
	 * wlan_ndev dereference, keeping the essid-path convention that a racing
	 * unbind can at worst mis-classify one in-flight install, never fault. */
	int wlan_ifindex;
};

struct zx_eth;

struct zx_eth_port {
	struct net_device *netdev;
	struct zx_eth *eth;
	int idx;
	u32 stats_rx_drops;
};

struct zx_eth {
	struct device *dev;
	void __iomem *base;	/* NPP + IDM + MACs + PP + TM (all in 2MB block) */
	void __iomem *pon_early;	/* 0x92000000-0x921bffff (PON_TOP early regs — CLA tables, etc) */
	void __iomem *topcrm;	/* clock control (small ioremap of 0x94000000) */
	void __iomem *fpga_base;	/* unified FPGA window 0x92000000 + 4 MiB
					 * — addresses every register described in
					 * zx-fpga-reg-tables.h. Overlaps with `base`
					 * and `pon_early`; we use it for the
					 * descriptor-table-driven `zx_fpga_write()`
					 * helper only (separate from existing direct
					 * tm_write/pp_write paths).
					 */
	/* [A02] Extra MMIO regions mapped from DT — needed by stock's
	 * zx_pon_clk_reset_init (SERDES band cal, sys_ctrl bit twiddle) and
	 * by gephy_ldo_timer_func temp compensation. Optional: probe()
	 * doesn't fail if these aren't in DT (older DTBs won't have them).
	 */
	void __iomem *sys_ctrl;	/* 0x94100000 (1 page) — sys_ctrl + temp sensor */
	void __iomem *pin_mux;	/* 0x94200000 (1 page) — pin routing config */
	void __iomem *pon_serdes;	/* 0x9fe00000 (1 MiB) — SERDES regs incl. band reg @+0x44 */

	int irq_idm;
	int irq_npp;
	int irq_tm;
	/* [A07][A08] Defensive PON / PP IRQs — fire ~0/ping on stock but the
	 * stock kmod registers them so we mirror for parity. PP IRQ exposes
	 * 4 useful event types (port migrate, static violation, hash
	 * collision, mac aged) — see gap matrix.
	 */
	int irq_pon;
	int irq_pp;

	/* TM subsystem (CPU↔switch via "sw" netdev).
	 * All TM DMA structures (BPPE, BP pool, RX desc, UP/DN TX desc) live in
	 * the carved 64 MiB region at phys 0x4C000000 (memremap'd here). Stock
	 * places them at fixed offsets — see iter20 finding doc.
	 */
	struct napi_struct tm_napi;
	struct net_device *sw_dev;
	void __iomem *carved_va;	/* memremap_wc(0x4C000000, 64 MiB) */
	void *bppe_cpu;		dma_addr_t bppe_dma;	/* u16 index array (carved offset) */
	void *bp_cpu;		dma_addr_t bp_dma;	/* BP backing store (carved offset) */
	void *rxdesc_cpu;	dma_addr_t rxdesc_dma;	/* RX desc ring 0 (UP) — carved offset */
	void *rxdesc_dn_cpu;	dma_addr_t rxdesc_dn_dma; /* RX desc ring 1 (DN/WAN) = rxdesc + 0x20000 */
	void *txdesc_cpu;	dma_addr_t txdesc_dma;	/* TX UP desc ring (carved offset) */
	void *dndesc_cpu;	dma_addr_t dndesc_dma;	/* TX DN desc ring (carved offset) */
	u32 tx_head;		/* current TX desc write index (0..1023) */
	spinlock_t tm_tx_lock;
	/* [txflowctrl 2026-07-04] TM TX-ring occupancy accounting (stock
	 * pon_tm_get_next_txdesc / pon_tm_check_tx_done_nolock port). All
	 * fields owned by tm_tx_lock. The HW consumed-count registers
	 * TM[0x10058] (UP) / TM[0x10068] (DN) low16 are CLEAR-ON-READ —
	 * every read MUST go through zx_sw_tx_reclaim_locked() or the
	 * accounting silently leaks (stats paths included). */
	u32 sw_tx_pending;	/* descs enqueued but not yet HW-consumed */
	u32 sw_tx_pending_max;	/* high-watermark (validation oracle) */
	u32 sw_tx_reclaimed;	/* total descs reclaimed via consumed-count */
	u32 sw_tx_full_drops;	/* enqueues refused: ring full (stock tx_full) */
	u32 sw_tx_queue_stops;	/* netif_stop_queue events on the conduit */
	u32 rx_head[TM_NUM_RX_QUEUES];		/* ring 0 (UP) per-q cursor */
	u32 rx_head_dn[TM_NUM_RX_QUEUES];	/* ring 1 (DN/WAN) per-q cursor */
	u32 tm_irq_count;
	u32 tm_napi_count;
	u32 tm_rx_count;
	u32 tm_rx_loopback_drops;
	u32 tm_tx_count;
	u32 tm_tx_dropped;
	/* Per-ingress-port RX counter (decoded from desc[6]: (desc[6]>>3 & 0x1F)-1).
	 * Used to identify the CPU-hairpin loopback ingress port empirically.
	 * The port that spikes 1:1 with tm_tx_count IS the hairpin source — we
	 * can then drop those frames to break the DUPs amplification loop.
	 * 32 slots: ingress is a 5-bit field minus 1, so values run -1..30; we
	 * shift by +1 to index.
	 */
	u32 tm_rx_per_ingress[32];
	/* BMU buffer-free credit (stock: allow_free_cnt) — preserved across calls.
	 * Refilled from tm[0x80dc] bits 8..13 when it hits 0.
	 */
	u32 bmu_free_credit;
	spinlock_t bmu_free_lock;
	u32 tm_bmu_free_ok;
	u32 tm_bmu_free_fail;
	/* Dedup set for FDB learning — 128 buckets, 1 bit each. Indexed by
	 * (src_mac[11] & 0x7f). Crude but avoids re-adding the same MAC
	 * repeatedly. Reset on reload.
	 */
	u8  fdb_learned[16];

	/* [Stage-3 WiFi observation, 2026-07-07] IDM RX ssid decode — ADDITIVE
	 * ONLY, delivery via napi_gro_receive is unchanged. Per the stock RE
	 * (findings/wifi_offload_feasibility_2026-07-04.md), IDM RX desc word1
	 * bits 16..18 = ssid (3-bit), bit 19 = ssid_valid. Mirrors the
	 * tm_rx_per_ingress[] counter pattern above: pure observation to learn
	 * whether/which ssid stock's WLAN vifs would stamp on this ring once
	 * ports 6/7 carry real MT7915 AP traffic. No behavior change.
	 */
	u32 idm_rx_count;
	u32 idm_rx_per_ssid[8];
	u32 idm_rx_ssid_invalid;	/* ssid_valid bit was 0 */

	/* [Stage-3 WiFi Phase B, 2026-07-23] IDM ring <-> WiFi-vif dispatch.
	 * BUILD-VERIFIED, UNTESTED ON HARDWARE — staged per
	 * findings/wifi_stage3_phaseB_dispatcher_spec_2026-07-07.md. The table
	 * defaults all-zero (enabled=false everywhere), so with nothing bound
	 * both the RX dispatch (zx_idm_poll) and TX stamp (zx_idm_xmit) are
	 * inert and behavior is byte-identical to today's baseline. Bindings
	 * are installed via the "wifi_bind" debugfs knob (zx_wifi_register_vif).
	 * node_index = ssid + idm*8. */
	struct zx_wifi_dispatch_node zx_wifi_dispatch[16];
	u32 idm_wifi_rx_dispatched;	/* RX frames handed to a bound vif */
	u32 idm_wifi_rx_nobind;		/* valid ssid, no bound/up vif -> local stack */
	u32 idm_wifi_tx_injected;	/* TX frames stamped with an ssid into the ring */
	/* [Phase C R1 validation 2026-07-28] dispatch debug/dial-in:
	 * idm_wifi_rx_dumped: one-shot hexdump budget for dispatched frames
	 * (debugfs "idm_rx_dump" — write 0 to re-arm 4 more dumps). Ground
	 * truth for the IDM RX payload format (offset/DA) which had never
	 * been eyeballed on HW.
	 * ft_wifi_dispatch_qx: 0 (default) = direct ndo_start_xmit into the
	 * vif (stock idm_fdb_forward parity) — HW-validated 2026-07-28 at
	 * 7.65 MB/s sustained; 1 = dev_queue_xmit (standard L2 injection,
	 * also works but measured ~4x slower on the same rig, 1.97 MB/s).
	 * Both modes deliver once the IP-checksum repair below is in place —
	 * the checksum was the sole delivery bug (an earlier "mac80211 eats
	 * the frames" reading came from a synthetic-flow probe whose fake
	 * next-hop DA 02:00:00:00:00:01 was legitimately dropped by AP-mode
	 * STA lookup). */
	u32 idm_wifi_rx_dumped;
	u32 ft_wifi_dispatch_qx;
	/* [Stage-3 WiFi Phase B.2, 2026-07-24] TM trap-RX fabric-ingress dispatch
	 * counters (fix-A validation proved port-6/7 ring-ingress traps deliver on
	 * the TM CPU rings with desc raw port >= 0x10, NOT on the IDM RX ring —
	 * findings/wifi_stage3_fixA_ondevice_validation_2026-07-07.md). */
	u32 tm_rx_fabric;		/* TM-RX frames with fabric/IDM ingress identity */
	u32 tm_wifi_rx_dispatched;	/* ...handed to a bound vif's stack (netif_rx) */
	u32 tm_wifi_rx_nobind;		/* ...no bound/up vif -> baseline DSA-demux path */
	u32 tm_wifi_rx_noparse;		/* ...bound but no recognizable frame at any offset */

	struct napi_struct napi;
	struct zx_eth_port ports[ZX_NPORTS];

	/* DMA descriptor ring (RX 16KB + TX 8KB, contiguous) */
	void *desc_cpu;
	dma_addr_t desc_dma;

	/* Shadow rings of SKB pointers */
	struct sk_buff *rx_skb[IDM_RX_RING_SIZE];
	struct sk_buff *tx_skb[IDM_TX_RING_SIZE];

	u32 rx_idx;	/* next slot to consume from HW */
	u32 tx_idx;	/* next slot to fill (producer) */
	u32 tx_done;	/* next slot to reclaim (consumer) */
	atomic_t tx_pending;

	spinlock_t tx_lock;

	bool started;

	/* PHY link-state tracking. Up to 4 GePHYs (one per LAN port).
	 * Populated in zx_eth_init_phys when each PHY is attached to the
	 * sw netdev. Last-known link state cached so adjust_link can
	 * detect transitions and write MAC[port].ctrl accordingly.
	 */
	struct phy_device *gephy[5];	/* [0..3]=LAN GePHYs, [4]=WAN ZX5201 (MDIO 0x08) */
	bool phy_was_link[5];

	/* Stock-init replay snapshots (CLA, PM, stock-bursts) are embedded
	 * as static tables in zx_{cla,pm,stock}_table.h — applied directly
	 * during probe, no firmware_request().
	 */

	/* [phase6/ft] per-flow offload slot map: tc cookie -> ram2 hash bucket,
	 * so FLOW_CLS_DESTROY can invalidate exactly that flow's bucket. */
#define ZX_FT_MAX_FLOWS	32
	struct {
		unsigned long	cookie;
		u16		raw;	/* raw HW hash (derives all 5 way buckets) */
		/* [C2 fix 2026-07-04] the poly-0 ram2 bucket (findings/
		 * qa_static_bughunt_2026-07-04.md C2): for DN flows,
		 * zx_ft_install_recipe ALSO writes the flow's entry at
		 * ram2[raw0 & 0xff] (poly-0 hash) because that is the slot the
		 * WAN-ingress lookup actually consults -- a SEPARATE ram2
		 * address from way0 (raw & 0xff) above. raw0/has_raw0 must be
		 * tracked per-flow so reserve() can collision-check it and
		 * untrack() can clear it; before this fix the poly-0 entry
		 * outlived FLOW_CLS_DESTROY (stale HW-forward of a dead tuple)
		 * and was never checked for collisions (two DN flows with
		 * distinct raw&0xff but equal raw0&0xff silently clobbered
		 * each other). has_raw0 is false for UP-direction entries
		 * (eth AND WiFi-ingress — no poly-0 write happens for those,
		 * see zx_ft_install_recipe) so untrack must not blindly zero
		 * ram2[raw0&0xff] for them. */
		u16		raw0;
		bool		has_raw0;
		u16		pm_slot;	/* per-(flow,dir) PM flow_info/next-hop slot */
		bool		used;
	} ft_flows[ZX_FT_MAX_FLOWS];

	/* [phase6/ft] PM EXTERNAL table carve (DDR above the kernel's RAM).
	 * The PON-PP packet-modify engine does NOT read the per-flow flow_info
	 * from the in-PM indirect ram0 — it DMA-FETCHES it from a DDR carve
	 * whose bases sit in PON_PP regs 0x923a0020 (pm) / 0x923a0024 (acl).
	 * Stock tm.ko zeroes this carve at init (aclRamInit) and writes the
	 * per-session flow_info there (pp_pm_set_external_flow_info); mainline
	 * never touched it, so every HW-forwarded frame was rewritten from
	 * ERASED DDR (0xff = all rewrite-enables set, nat ports 0xffff,
	 * next_hop_idx 511 = empty -> MACs/IPs zeroed) and the download
	 * black-holed at the client NIC. Root-caused on-device 2026-07-04.
	 */
	void __iomem	*pm_ext;	/* mapped carve (ZX_PM_EXT_SPAN bytes) */
	u32		pm_ext_phys;	/* carve phys base (= acl_base - 0x20000) */

	/* [phase6/ft] UP-direction (LAN->WAN egress) HW offload enable.
	 * 0 = decline UP installs (UP rides the SW flowtable fast-path; the
	 * historical default — but under full DN load the trapped UP ACKs
	 * RED-starve, TCP collapses and the trap queue wedges, QA 2026-07-04).
	 * 1 = install the UP recipe in HW too (debugfs "ftup"). */
	u32		ft_up_en;

	/* [Stage-3 WiFi Phase C 2026-07-27] WiFi-egress HW offload enable.
	 * 0 (DEFAULT) = the H4 guard declines wlan-vif-egress flows exactly as
	 * before Phase C — an unconfigured boot is behavior-identical to the
	 * pre-Phase-C baseline. 1 (debugfs "ftwifi") = a FLOW_CLS_REPLACE whose
	 * egress dev is a BOUND wifi_bind vif resolves to the WLAN logical port
	 * essid = 0x10|(idm<<3)|ssid and installs the DN hardfast recipe with
	 * gemport_uni_id = essid (spec:
	 * findings/wifi_stage3_phaseC_offload_spec_2026-07-25.md §1.5/§3). */
	u32		ft_wifi_en;

	/* [H5 fix 2026-07-04] PM indirect-RAM write-verify accounting
	 * (findings/qa_static_bughunt_2026-07-04.md H5). zx_pp_pm_write_verify()
	 * reads each FT-install PM write back and retries on mismatch; these
	 * count readback-confirmed commits / commits that needed >=1 retry /
	 * persistent failures, so a regression that drops the verify (or the
	 * rc-check) is observable via debugfs `stats` + regress.py
	 * pm_write_verify even when the bare write happens to commit anyway. */
	u64		ft_pm_verify_ok;
	u64		ft_pm_verify_retry;
	u64		ft_pm_verify_fail;

	/* [WiFi productionization 2026-08-01] netdevice notifier for
	 * auto-binding wlan interfaces to idm/ssid slots. */
	struct notifier_block wlan_nb;
};

/* ============================================================
 *   Low-level helpers
 * ============================================================
 */

static inline u32 npp_read(struct zx_eth *e, u32 off)
{
	return readl(e->base + off);
}

static inline void npp_write(struct zx_eth *e, u32 off, u32 val)
{
	writel(val, e->base + off);
}

static inline void npp_or(struct zx_eth *e, u32 off, u32 bits)
{
	npp_write(e, off, npp_read(e, off) | bits);
}

static inline void npp_and(struct zx_eth *e, u32 off, u32 mask)
{
	npp_write(e, off, npp_read(e, off) & mask);
}

static inline u32 mac_off(int port, u32 off)
{
	return (port + 1) * MAC_STRIDE + off;
}

/* Use streaming DMA for SKB data; descriptor uses skb_data_phys */
static dma_addr_t zx_map_rx_skb(struct zx_eth *e, struct sk_buff *skb)
{
	return dma_map_single(e->dev, skb->data, IDM_RX_SKB_SIZE - IDM_RX_SKB_HEADROOM,
			      DMA_FROM_DEVICE);
