# -*- coding: utf-8 -*-
# Decompile EVERY function (named + FUN_*) of the current program into ONE
# concatenated .c file at <out_dir>/decomp_all_<modname>.c, mirroring the
# format already used in tasks/00.10.02.re-stock-kmods/findings/decomp_all_*.c.
#
# @category ZXIC
# @runtime Jython

import os
import re
from ghidra.app.decompiler import DecompInterface, DecompileOptions

DECOMPILE_TIMEOUT = 60
SKIP_PREFIXES = ("__aeabi_", "_GLOBAL_", "$d", "$t", "$a")

args = getScriptArgs()
out_dir = args[0] if len(args) >= 1 else "/home/ubuntu/Projects/MYSELF/ZTE/tasks/00.10.02.re-stock-kmods/findings"
try: os.makedirs(out_dir)
except OSError: pass

prog_name = currentProgram.getName()
mod_base = prog_name.rsplit(".", 1)[0]                 # strip ".ko"
mod_base = mod_base.replace("-", "_")                  # filename-safe
out_file = os.path.join(out_dir, "decomp_all_" + mod_base + ".c")
print("output: " + out_file)

decomp = DecompInterface()
decomp.setOptions(DecompileOptions())
decomp.openProgram(currentProgram)

func_mgr = currentProgram.getFunctionManager()
funcs = list(func_mgr.getFunctions(True))
print("total functions: " + str(len(funcs)))

# Stable order: by entry address
funcs.sort(key=lambda f: int(str(f.getEntryPoint()), 16))

ok = 0
fail = 0
with open(out_file, "w") as fp:
    fp.write("/* Concatenated Ghidra decomp of " + prog_name + " */\n")
    fp.write("/* " + str(len(funcs)) + " functions, generated by dump_all_concat.py */\n\n")
    for f in funcs:
        name = str(f.getName())
        if any(name.startswith(p) for p in SKIP_PREFIXES):
            continue
        addr = str(f.getEntryPoint())
        dr = decomp.decompileFunction(f, DECOMPILE_TIMEOUT, monitor)
        if dr and dr.decompileCompleted():
            fp.write("/* ============= FUNCTION: " + name + " @ " + addr + " ============= */\n\n")
            fp.write(dr.getDecompiledFunction().getC())
            fp.write("\n\n")
            ok += 1
        else:
            fp.write("/* ============= FUNCTION: " + name + " @ " + addr + " (DECOMP FAILED) ============= */\n\n")
            fail += 1

print("decomp OK: " + str(ok) + "  FAILED: " + str(fail))
print("wrote " + out_file)
