/* Concatenated Ghidra decomp of shellproc.ko */
/* 74 functions, generated by dump_all_concat.py */

/* ============= FUNCTION: myfile_read @ 00010000 ============= */


undefined4 myfile_read(int param_1,int param_2,undefined4 param_3,undefined4 param_4)

{
  undefined4 uVar1;
  undefined4 uVar2;
  uint uVar3;
  undefined4 uStack_10;
  
  if (param_2 != 0 && param_1 != 0) {
    uVar3 = (uint)&uStack_10 & 0xffffe000;
    uVar2 = *(undefined4 *)(uVar3 + 8);
    *(undefined4 *)(uVar3 + 8) = 0;
    uStack_10 = param_4;
    uVar1 = (**(code **)(*(int *)(param_1 + 0x14) + 8))();
    *(undefined4 *)(((uint)&uStack_10 & 0xffffe000) + 8) = uVar2;
    return uVar1;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: get_task_full_path.constprop.9 @ 00010058 ============= */


size_t get_task_full_path_constprop_9
                 (int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  void *pvVar1;
  int iVar2;
  int iVar3;
  size_t __n;
  
  iVar2 = *(int *)(param_1 + 0x18c);
  if (((iVar2 != 0) && (iVar3 = *(int *)(iVar2 + 0x188), iVar3 != 0)) &&
     (iVar2 = __get_free_pages(0x800d0,0,param_3,iVar2,param_4), iVar2 != 0)) {
    pvVar1 = (void *)d_path(iVar3 + 8,iVar2,0x1000);
    if (pvVar1 == (void *)0x0) {
      __n = 0xffffffff;
    }
    else {
      __n = (iVar2 + 0xfff) - (int)pvVar1;
      if (0x7e < (int)__n) {
        __n = 0x7f;
      }
      pvVar1 = memcpy(&task_path,pvVar1,__n);
      *(undefined1 *)((int)pvVar1 + __n) = 0;
    }
    free_pages(iVar2,0);
    return __n;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: myfile_open.constprop.10 @ 000100f4 ============= */


uint myfile_open_constprop_10(undefined4 param_1)

{
  uint uVar1;
  
  uVar1 = filp_open(param_1,0,0);
  if (uVar1 < 0xfffff001) {
    return uVar1;
  }
  printk("filp_open [%s] failed.\n",param_1);
  return 0;
}



/* ============= FUNCTION: myfile_lseek.constprop.14 @ 00010128 ============= */


undefined4 myfile_lseek_constprop_14(int param_1,int param_2)

{
  undefined4 uVar1;
  code *pcVar2;
  undefined4 uVar3;
  undefined4 local_18 [2];
  
  if (param_1 != 0) {
    uVar3 = *(undefined4 *)(((uint)local_18 & 0xffffe000) + 8);
    *(undefined4 *)(((uint)local_18 & 0xffffe000) + 8) = 0;
    local_18[0] = 0;
    pcVar2 = *(code **)(*(int *)(param_1 + 0x14) + 4);
    uVar1 = (*pcVar2)(param_1,pcVar2,param_2,param_2 >> 0x1f);
    *(undefined4 *)(((uint)local_18 & 0xffffe000) + 8) = uVar3;
    return uVar1;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: get_elf_header.constprop.5 @ 00010188 ============= */


undefined4
get_elf_header_constprop_5
          (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int iVar1;
  
  myfile_lseek_constprop_14(param_1,0,param_3,param_4,param_4);
  iVar1 = myfile_read(param_1,Ehdr32,0x34);
  if (iVar1 != 0x34) {
    return 0xffffffff;
  }
  is_big_endian = (uint)(Ehdr32[5] == '\x02');
  is_32bit_elf = (uint)(Ehdr32[4] != '\x02');
  if ((Ehdr32[5] == '\x02') == 0) {
    return 0;
  }
  Ehdr32._16_2_ = Ehdr32._16_2_ << 8 | (ushort)Ehdr32._16_2_ >> 8;
  Ehdr32._18_2_ = Ehdr32._18_2_ << 8 | (ushort)Ehdr32._18_2_ >> 8;
  Ehdr32._20_4_ =
       Ehdr32._20_4_ << 0x18 | ((uint)Ehdr32._20_4_ >> 8 & 0xff) << 0x10 |
       ((uint)Ehdr32._20_4_ >> 0x10 & 0xff) << 8 | (uint)Ehdr32._20_4_ >> 0x18;
  Ehdr32._24_4_ =
       Ehdr32._24_4_ << 0x18 | ((uint)Ehdr32._24_4_ >> 8 & 0xff) << 0x10 |
       ((uint)Ehdr32._24_4_ >> 0x10 & 0xff) << 8 | (uint)Ehdr32._24_4_ >> 0x18;
  Ehdr32._28_4_ =
       Ehdr32._28_4_ << 0x18 | ((uint)Ehdr32._28_4_ >> 8 & 0xff) << 0x10 |
       ((uint)Ehdr32._28_4_ >> 0x10 & 0xff) << 8 | (uint)Ehdr32._28_4_ >> 0x18;
  Ehdr32._32_4_ =
       Ehdr32._32_4_ << 0x18 | ((uint)Ehdr32._32_4_ >> 8 & 0xff) << 0x10 |
       ((uint)Ehdr32._32_4_ >> 0x10 & 0xff) << 8 | (uint)Ehdr32._32_4_ >> 0x18;
  Ehdr32._36_4_ =
       Ehdr32._36_4_ << 0x18 | ((uint)Ehdr32._36_4_ >> 8 & 0xff) << 0x10 |
       ((uint)Ehdr32._36_4_ >> 0x10 & 0xff) << 8 | (uint)Ehdr32._36_4_ >> 0x18;
  Ehdr32._40_2_ = Ehdr32._40_2_ << 8 | (ushort)Ehdr32._40_2_ >> 8;
  Ehdr32._42_2_ = Ehdr32._42_2_ << 8 | (ushort)Ehdr32._42_2_ >> 8;
  Ehdr32._44_2_ = Ehdr32._44_2_ << 8 | (ushort)Ehdr32._44_2_ >> 8;
  Ehdr32._46_2_ = Ehdr32._46_2_ << 8 | (ushort)Ehdr32._46_2_ >> 8;
  Ehdr32._48_2_ = Ehdr32._48_2_ << 8 | (ushort)Ehdr32._48_2_ >> 8;
  Ehdr32._50_2_ = Ehdr32._50_2_ << 8 | (ushort)Ehdr32._50_2_ >> 8;
  return 0;
}



/* ============= FUNCTION: get_data @ 00010290 ============= */


int get_data(undefined4 param_1,undefined4 param_2,uint param_3,char *param_4)

{
  int iVar1;
  uint uVar2;
  
  if (param_4 == (char *)0x0) {
    param_4 = "unkown";
  }
  if (param_3 == 0) {
    iVar1 = 0;
  }
  else {
    iVar1 = myfile_lseek_constprop_14();
    if (iVar1 < 0) {
      printk("Unable to seek to 0x%lx for %s\n",param_2,param_4);
      iVar1 = 0;
    }
    else if ((param_3 < 0x200000) && (iVar1 = __kmalloc(param_3,0xd0), iVar1 != 0)) {
      uVar2 = myfile_read(param_1,iVar1,param_3);
      if (uVar2 != param_3) {
        printk("Unable to read in 0x%lx bytes of %s\n",param_3,param_4);
        kfree(iVar1);
        iVar1 = 0;
      }
    }
    else {
      printk("Out of memory allocating 0x%lx bytes for %s\n",param_3,param_4);
      iVar1 = 0;
    }
  }
  return iVar1;
}



/* ============= FUNCTION: get_32bit_elf_symbols @ 00010364 ============= */


uint * get_32bit_elf_symbols(undefined4 param_1,int param_2,undefined4 param_3,undefined4 param_4)

{
  uint *puVar1;
  uint *puVar2;
  int iVar3;
  uint uVar4;
  int iVar5;
  uint uVar6;
  uint uVar7;
  
  if (*(int *)(param_2 + 0x24) == 0x10) {
    puVar2 = (uint *)get_data(param_1,*(undefined4 *)(param_2 + 0x10),
                              *(undefined4 *)(param_2 + 0x14),"symtab shndx");
    if (puVar2 != (uint *)0x0) {
      if ((is_big_endian != 0) &&
         (iVar3 = __aeabi_uidiv(*(undefined4 *)(param_2 + 0x14),*(undefined4 *)(param_2 + 0x24)),
         0 < iVar3)) {
        iVar5 = 0;
        puVar1 = puVar2;
        do {
          iVar5 = iVar5 + 1;
          uVar7 = *puVar1;
          uVar6 = puVar1[1];
          uVar4 = puVar1[2];
          *puVar1 = uVar7 << 0x18 | (uVar7 >> 8 & 0xff) << 0x10 | (uVar7 >> 0x10 & 0xff) << 8 |
                    uVar7 >> 0x18;
          puVar1[1] = uVar6 << 0x18 | (uVar6 >> 8 & 0xff) << 0x10 | (uVar6 >> 0x10 & 0xff) << 8 |
                      uVar6 >> 0x18;
          puVar1[2] = uVar4 << 0x18 | (uVar4 >> 8 & 0xff) << 0x10 | (uVar4 >> 0x10 & 0xff) << 8 |
                      uVar4 >> 0x18;
          *(ushort *)((int)puVar1 + 0xe) =
               *(ushort *)((int)puVar1 + 0xe) << 8 | *(ushort *)((int)puVar1 + 0xe) >> 8;
          puVar1 = puVar1 + 4;
        } while (iVar3 != iVar5);
      }
    }
    return puVar2;
  }
  printk("Invalid entsize of section, %d, should be %d\n",*(int *)(param_2 + 0x24),0x10,param_4,
         param_4);
  return (uint *)0x0;
}



/* ============= FUNCTION: get_32bit_section_headers.constprop.7 @ 00010424 ============= */


undefined4 get_32bit_section_headers_constprop_7(undefined4 param_1)

{
  uint *puVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  uint uVar9;
  uint uVar10;
  uint uVar11;
  uint uVar12;
  
  if (section_headers == (uint *)0x0) {
    if (Ehdr32._46_2_ != 0x28) {
      printk("Invalid size of section header %d, should be %d\n",Ehdr32._46_2_,0x34);
      return 0xffffffff;
    }
    section_headers =
         (uint *)get_data(param_1,Ehdr32._32_4_,(uint)(ushort)Ehdr32._48_2_ * 0x28,"section headers"
                         );
    if (section_headers == (uint *)0x0) {
      return 0xffffffff;
    }
    if ((is_big_endian != 0) && (Ehdr32._48_2_ != 0)) {
      iVar4 = 0;
      puVar1 = section_headers;
      do {
        uVar10 = *puVar1;
        iVar4 = iVar4 + 1;
        uVar9 = puVar1[1];
        uVar8 = puVar1[2];
        uVar7 = puVar1[3];
        uVar6 = puVar1[4];
        uVar5 = puVar1[5];
        uVar12 = puVar1[6];
        uVar11 = puVar1[7];
        uVar2 = puVar1[8];
        uVar3 = puVar1[9];
        *puVar1 = uVar10 << 0x18 | (uVar10 >> 8 & 0xff) << 0x10 | (uVar10 >> 0x10 & 0xff) << 8 |
                  uVar10 >> 0x18;
        puVar1[1] = uVar9 << 0x18 | (uVar9 >> 8 & 0xff) << 0x10 | (uVar9 >> 0x10 & 0xff) << 8 |
                    uVar9 >> 0x18;
        puVar1[2] = uVar8 << 0x18 | (uVar8 >> 8 & 0xff) << 0x10 | (uVar8 >> 0x10 & 0xff) << 8 |
                    uVar8 >> 0x18;
        puVar1[3] = uVar7 << 0x18 | (uVar7 >> 8 & 0xff) << 0x10 | (uVar7 >> 0x10 & 0xff) << 8 |
                    uVar7 >> 0x18;
        puVar1[4] = uVar6 << 0x18 | (uVar6 >> 8 & 0xff) << 0x10 | (uVar6 >> 0x10 & 0xff) << 8 |
                    uVar6 >> 0x18;
        puVar1[5] = uVar5 << 0x18 | (uVar5 >> 8 & 0xff) << 0x10 | (uVar5 >> 0x10 & 0xff) << 8 |
                    uVar5 >> 0x18;
        puVar1[6] = uVar12 << 0x18 | (uVar12 >> 8 & 0xff) << 0x10 | (uVar12 >> 0x10 & 0xff) << 8 |
                    uVar12 >> 0x18;
        puVar1[7] = uVar11 << 0x18 | (uVar11 >> 8 & 0xff) << 0x10 | (uVar11 >> 0x10 & 0xff) << 8 |
                    uVar11 >> 0x18;
        puVar1[9] = uVar3 << 0x18 | (uVar3 >> 8 & 0xff) << 0x10 | (uVar3 >> 0x10 & 0xff) << 8 |
                    uVar3 >> 0x18;
        puVar1[8] = uVar2 << 0x18 | (uVar2 >> 8 & 0xff) << 0x10 | (uVar2 >> 0x10 & 0xff) << 8 |
                    uVar2 >> 0x18;
        puVar1 = puVar1 + 10;
      } while (iVar4 < (int)(uint)(ushort)Ehdr32._48_2_);
      return 0;
    }
  }
  return 0;
}



/* ============= FUNCTION: get_string_table.part.0.constprop.13 @ 00010548 ============= */


void get_string_table_part_0_constprop_13
               (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  uint uVar1;
  int iVar2;
  
  uVar1 = (uint)(ushort)Ehdr32._50_2_;
  if (uVar1 == 0) {
    return;
  }
  if (uVar1 < (ushort)Ehdr32._48_2_) {
    iVar2 = section_headers + uVar1 * 0x28;
    if (*(int *)(iVar2 + 0x14) != 0) {
      string_table = get_data(param_1,*(undefined4 *)(iVar2 + 0x10),*(int *)(iVar2 + 0x14),
                              "string table",param_4);
    }
    string_table_length = 0;
    if (string_table != 0) {
      string_table_length = *(undefined4 *)(iVar2 + 0x14);
    }
    return;
  }
  return;
}



/* ============= FUNCTION: func_insert @ 000105b4 ============= */


undefined4 func_insert(int *param_1,int *param_2)

{
  int *piVar1;
  int iVar2;
  int iVar3;
  
  piVar1 = param_1;
  iVar3 = 0;
  do {
    while( true ) {
      iVar2 = *piVar1;
      if (iVar2 == 0) {
        *param_2 = iVar3;
        param_2[1] = 0;
        param_2[2] = 0;
        *piVar1 = (int)param_2;
        rb_insert_color(param_2,param_1);
        return 0;
      }
      piVar1 = (int *)(iVar2 + 4);
      iVar3 = iVar2;
      if (*(uint *)(iVar2 + 0xc) < (uint)param_2[4]) break;
      piVar1 = (int *)(iVar2 + 8);
    }
  } while (*(uint *)(iVar2 + 0x10) <= (uint)param_2[3]);
  return 0xffffffff;
}



/* ============= FUNCTION: func_search @ 0001062c ============= */


void func_search(int *param_1,uint param_2)

{
  int iVar1;
  
  iVar1 = *param_1;
  if (iVar1 == 0) {
    return;
  }
  do {
    while (param_2 < *(uint *)(iVar1 + 0xc)) {
      iVar1 = *(int *)(iVar1 + 8);
      if (iVar1 == 0) {
        return;
      }
    }
    if (param_2 < *(uint *)(iVar1 + 0x10)) {
      return;
    }
    iVar1 = *(int *)(iVar1 + 4);
  } while (iVar1 != 0);
  return;
}



/* ============= FUNCTION: func_print @ 00010670 ============= */


void func_print(void)

{
  int iVar1;
  
  iVar1 = rb_first();
  if (iVar1 == 0) {
    return;
  }
  do {
    printk("func %s : %.8x-%.8x\n",iVar1 + 0x14,*(undefined4 *)(iVar1 + 0xc),
           *(undefined4 *)(iVar1 + 0x10));
    iVar1 = rb_next(iVar1);
  } while (iVar1 != 0);
  return;
}



/* ============= FUNCTION: build_func_usyms @ 000106ac ============= */


/* WARNING: Restarted to delay deadcode elimination for space: ram */

void * build_func_usyms(undefined4 param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  void *pvVar5;
  int iVar6;
  size_t __n;
  uint uVar7;
  char *__s2;
  uint uVar8;
  uint __n_00;
  uint *puVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  int iVar13;
  int iVar14;
  char *__src;
  void *local_54;
  uint local_4c;
  uint local_48;
  int local_34;
  uint *local_30;
  
  iVar1 = get_task_full_path_constprop_9();
  if ((iVar1 < 1) || (iVar1 = myfile_open_constprop_10(&task_path), iVar1 == 0)) {
    return (void *)0x0;
  }
  if (string_table != 0) {
    kfree();
    string_table = 0;
  }
  if (section_headers != 0) {
    kfree();
    section_headers = 0;
  }
  string_table_length = 0;
  iVar2 = get_elf_header_constprop_5(iVar1);
  if (iVar2 < 0) {
    filp_close(iVar1,0);
    return (void *)0x0;
  }
  cur_task = param_1;
  if (is_32bit_elf == 0) {
    printk("\nIt is not 32 bit elf file\n");
    goto LAB_00010cac;
  }
  iVar2 = get_32bit_section_headers_constprop_7(iVar1);
  if (iVar2 < 0) goto LAB_00010cac;
  if (string_table == 0) {
    get_string_table_part_0_constprop_13(iVar1);
  }
  local_54 = (void *)kmalloc_order(0x6800,0xd0,3);
  if (local_54 == (void *)0x0) {
    printk("node is NULL!,%s\n","build_elf_addr_symbol");
    goto LAB_00010cac;
  }
  if (Ehdr32._48_2_ == 0) {
LAB_00010cc8:
    local_4c = 0x200;
LAB_00010bd0:
    uVar7 = 0;
    pvVar5 = local_54;
    do {
      iVar2 = func_insert(&mytree,pvVar5);
      uVar7 = uVar7 + 1;
      pvVar5 = (void *)((int)pvVar5 + 0x34);
      if (iVar2 < 0) break;
    } while (uVar7 < local_4c);
  }
  else {
    local_34 = 0;
    local_30 = (uint *)0x0;
    iVar10 = 0;
    iVar2 = section_headers;
    do {
      if ((*(int *)(iVar2 + 4) == 9) && (iVar12 = *(int *)(iVar2 + 0x14), iVar12 != 0)) {
        iVar14 = *(int *)(iVar2 + 0x24);
        local_34 = __aeabi_uidiv(iVar12,iVar14);
        if (iVar14 == 8) {
          local_30 = (uint *)get_data(iVar1,*(undefined4 *)(iVar2 + 0x10),iVar12,"rel section");
          if (local_30 != (uint *)0x0) {
            if ((is_big_endian != 0) &&
               (iVar12 = __aeabi_uidiv(*(undefined4 *)(iVar2 + 0x14),*(undefined4 *)(iVar2 + 0x24)),
               0 < iVar12)) {
              iVar14 = 0;
              puVar9 = local_30;
              do {
                iVar14 = iVar14 + 1;
                uVar7 = *puVar9;
                uVar8 = puVar9[1];
                *puVar9 = uVar7 << 0x18 | (uVar7 >> 8 & 0xff) << 0x10 | (uVar7 >> 0x10 & 0xff) << 8
                          | uVar7 >> 0x18;
                puVar9[1] = uVar8 << 0x18 | (uVar8 >> 8 & 0xff) << 0x10 |
                            (uVar8 >> 0x10 & 0xff) << 8 | uVar8 >> 0x18;
                puVar9 = puVar9 + 2;
              } while (iVar12 != iVar14);
            }
          }
        }
        else {
          printk("Invalid entsize of section, %d, should be %d\n",iVar14,8);
          local_30 = (uint *)0x0;
        }
      }
      iVar10 = iVar10 + 1;
      iVar2 = iVar2 + 0x28;
    } while (iVar10 < (int)(uint)(ushort)Ehdr32._48_2_);
    if ((ushort)Ehdr32._48_2_ == 0) goto LAB_00010cc8;
    uVar7 = 0;
    iVar10 = 0;
    local_4c = 0x200;
    iVar12 = 0;
    local_48 = 0;
    iVar2 = section_headers;
    do {
      if ((*(int *)(iVar2 + 4) == 0xb || *(int *)(iVar2 + 4) == 2) &&
         (iVar3 = get_32bit_elf_symbols(iVar1,iVar2), iVar14 = string_table, iVar3 != 0)) {
        uVar8 = *(uint *)(iVar2 + 0x18);
        if (uVar8 == (ushort)Ehdr32._50_2_) {
          local_48 = string_table_length;
          iVar4 = __aeabi_uidiv(*(undefined4 *)(iVar2 + 0x14),*(undefined4 *)(iVar2 + 0x24));
          if (0 < iVar4) goto LAB_00010948;
        }
        else {
          if ((uVar8 < (ushort)Ehdr32._48_2_) &&
             (iVar14 = section_headers + uVar8 * 0x28, *(int *)(iVar14 + 4) == 3)) {
            iVar10 = get_data(iVar1,*(undefined4 *)(iVar14 + 0x10),*(undefined4 *)(iVar14 + 0x14),
                              "string table");
            if (iVar10 == 0) {
              local_48 = 0;
            }
            else {
              local_48 = *(uint *)(iVar14 + 0x14);
            }
          }
          iVar4 = __aeabi_uidiv(*(undefined4 *)(iVar2 + 0x14),*(undefined4 *)(iVar2 + 0x24));
          iVar14 = iVar10;
          if (0 < iVar4) {
LAB_00010948:
            iVar11 = 0;
            iVar10 = iVar3 + 0x10;
            do {
              while ((((*(short *)(iVar10 + -2) == 0 && (*(int *)(iVar2 + 4) != 0xb)) ||
                      (iVar14 == 0 || (*(byte *)(iVar10 + -4) & 0xf) != 2)) ||
                     (*(uint *)(iVar10 + -8) < 8))) {
LAB_0001096c:
                iVar11 = iVar11 + 1;
                iVar10 = iVar10 + 0x10;
                if (iVar4 == iVar11) goto LAB_00010a94;
              }
              if (*(uint *)(iVar10 + -0x10) < local_48) {
                __src = (char *)(iVar14 + *(uint *)(iVar10 + -0x10));
              }
              else {
                __src = "<corrupt>";
              }
              strncpy((char *)((int)local_54 + uVar7 * 0x34 + 0x14),__src,0x1f);
              if (*(int *)(iVar2 + 4) == 0xb) {
                if ((local_30 != (uint *)0x0) && (local_34 != 0)) {
                  iVar13 = 0;
                  puVar9 = local_30;
                  do {
                    __s2 = "<corrupt>";
                    iVar13 = iVar13 + 1;
                    uVar8 = *(uint *)(iVar3 + (puVar9[1] >> 8) * 0x10);
                    if (uVar8 < local_48) {
                      __s2 = (char *)(iVar14 + uVar8);
                    }
                    iVar6 = strcmp(__src,__s2);
                    if (iVar6 == 0) {
                      iVar13 = user_va2pa(cur_task,*puVar9);
                      if ((iVar13 != 0) &&
                         (uVar8 = *(uint *)(iVar13 + -0x80000000), 0x3fffffff < uVar8)) {
                        *(uint *)((int)local_54 + uVar7 * 0x34 + 0xc) = uVar8;
                        *(uint *)((int)local_54 + uVar7 * 0x34 + 0x10) =
                             uVar8 + *(int *)(iVar10 + -8);
                        goto LAB_00010a14;
                      }
                      break;
                    }
                    puVar9 = puVar9 + 2;
                  } while (iVar13 != local_34);
                }
                goto LAB_0001096c;
              }
              *(undefined4 *)((int)local_54 + uVar7 * 0x34 + 0xc) = *(undefined4 *)(iVar10 + -0xc);
              *(int *)((int)local_54 + uVar7 * 0x34 + 0x10) =
                   *(int *)(iVar10 + -8) + *(int *)(iVar10 + -0xc);
LAB_00010a14:
              uVar7 = uVar7 + 1;
              if (uVar7 < local_4c) goto LAB_0001096c;
              uVar8 = local_4c * 0x34;
              __n_00 = uVar8 + 0x6800;
              pvVar5 = (void *)__kmalloc(__n_00,0xd0);
              if (pvVar5 == (void *)0x0 || local_54 == (void *)0x0) {
                kfree(local_54);
                if (pvVar5 == (void *)0x0) {
                  if (iVar14 != string_table) {
                    kfree(iVar14);
                  }
                  kfree(iVar3);
                  goto LAB_00010cac;
                }
              }
              else {
                if (uVar8 <= __n_00) {
                  __n_00 = uVar8;
                }
                memcpy(pvVar5,local_54,__n_00);
                kfree(local_54);
              }
              iVar11 = iVar11 + 1;
              local_4c = local_4c + 0x200;
              iVar10 = iVar10 + 0x10;
              local_54 = pvVar5;
            } while (iVar4 != iVar11);
          }
LAB_00010a94:
          if (iVar14 != string_table) {
            kfree(iVar14);
            iVar14 = 0;
          }
        }
        kfree(iVar3);
        iVar10 = iVar14;
      }
      iVar12 = iVar12 + 1;
      iVar2 = iVar2 + 0x28;
    } while (iVar12 < (int)(uint)(ushort)Ehdr32._48_2_);
    if (local_4c != 0) goto LAB_00010bd0;
  }
  if (local_54 != (void *)0x0) {
    filp_close(iVar1,0);
    __n = strlen(&task_path);
    if (0x7e < (int)__n) {
      __n = 0x7f;
    }
    memcpy(last_task_path,&task_path,__n);
    last_task_path[0x7f] = 0;
    return local_54;
  }
LAB_00010cac:
  filp_close(iVar1,0);
  last_task_path[0] = 0;
  return (void *)0x0;
}



/* ============= FUNCTION: usyms_lookup_name @ 00010d30 ============= */


/* WARNING: Restarted to delay deadcode elimination for space: ram */

undefined8 * usyms_lookup_name(undefined4 param_1,char *param_2,char *param_3)

{
  int iVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  int iVar5;
  size_t __n;
  char *__s2;
  uint uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  uint local_40;
  int local_30;
  
  if (param_3 == (char *)0x0) {
    iVar1 = get_task_full_path_constprop_9();
    if (iVar1 < 1) {
      return (undefined8 *)0x0;
    }
    param_3 = &task_path;
  }
  printk("open file %s\n",param_3);
  iVar1 = myfile_open_constprop_10(param_3);
  if (iVar1 == 0) {
    return (undefined8 *)0x0;
  }
  if (string_table != 0) {
    kfree();
    string_table = 0;
  }
  if (section_headers != 0) {
    kfree();
    section_headers = 0;
  }
  string_table_length = 0;
  iVar2 = get_elf_header_constprop_5(iVar1);
  if (iVar2 < 0) {
    filp_close(iVar1,0);
    return (undefined8 *)0x0;
  }
  cur_task = param_1;
  if (is_32bit_elf == 0) {
    printk("\nIt is not 32 bit elf file\n");
  }
  else {
    iVar2 = get_32bit_section_headers_constprop_7(iVar1);
    if (-1 < iVar2) {
      if (string_table == 0) {
        get_string_table_part_0_constprop_13(iVar1);
      }
      if (Ehdr32._48_2_ != 0) {
        iVar2 = 0;
        local_40 = 0;
        iVar7 = 0;
        local_30 = -1;
        iVar11 = section_headers;
        do {
          if ((*(int *)(iVar11 + 4) == 0xb || *(int *)(iVar11 + 4) == 2) &&
             (iVar3 = get_32bit_elf_symbols(iVar1,iVar11), iVar3 != 0)) {
            uVar6 = *(uint *)(iVar11 + 0x18);
            if (uVar6 == (ushort)Ehdr32._50_2_) {
              iVar8 = __aeabi_uidiv(*(undefined4 *)(iVar11 + 0x14),*(undefined4 *)(iVar11 + 0x24));
              local_40 = string_table_length;
              iVar2 = string_table;
              if (0 < iVar8) goto LAB_00010eec;
            }
            else {
              if ((uVar6 < (ushort)Ehdr32._48_2_) &&
                 (iVar8 = uVar6 * 0x28 + section_headers, *(int *)(iVar8 + 4) == 3)) {
                iVar2 = get_data(iVar1,*(undefined4 *)(iVar8 + 0x10),*(undefined4 *)(iVar8 + 0x14),
                                 "string table");
                if (iVar2 == 0) {
                  local_40 = 0;
                }
                else {
                  local_40 = *(uint *)(iVar8 + 0x14);
                }
              }
              iVar8 = __aeabi_uidiv(*(undefined4 *)(iVar11 + 0x14),*(undefined4 *)(iVar11 + 0x24));
              if (0 < iVar8) {
LAB_00010eec:
                iVar9 = 0;
                iVar10 = iVar3;
                do {
                  uVar6 = *(byte *)(iVar10 + 0xc) & 0xf;
                  if ((iVar2 != 0) && (uVar6 - 1 < 2)) {
                    __s2 = "<corrupt>";
                    uVar4 = *(uint *)(iVar3 + iVar9 * 0x10);
                    if (uVar4 < local_40) {
                      __s2 = (char *)(iVar2 + uVar4);
                    }
                    iVar5 = strcmp(param_2,__s2);
                    if (iVar5 == 0) {
                      sym_info._0_4_ = *(undefined4 *)(iVar10 + 4);
                      sym_info._4_2_ = (undefined2)uVar6;
                      sym_info._6_2_ = (undefined2)*(undefined4 *)(iVar10 + 8);
                      local_30 = 0;
                      break;
                    }
                  }
                  iVar9 = iVar9 + 1;
                  iVar10 = iVar10 + 0x10;
                } while (iVar9 < iVar8);
              }
              if (iVar2 != string_table) {
                kfree(iVar2);
                iVar2 = 0;
              }
            }
            kfree(iVar3);
          }
          iVar7 = iVar7 + 1;
          iVar11 = iVar11 + 0x28;
        } while (iVar7 < (int)(uint)(ushort)Ehdr32._48_2_);
        if (local_30 != -1) {
          filp_close(iVar1,0);
          __n = strlen(param_3);
          if (0x7e < (int)__n) {
            __n = 0x7f;
          }
          memcpy(last_task_path,param_3,__n);
          last_task_path[0x7f] = 0;
          return &sym_info;
        }
      }
    }
  }
  filp_close(iVar1,0);
  last_task_path[0] = 0;
  return (undefined8 *)0x0;
}



/* ============= FUNCTION: usyms_lookup_addr @ 000110a8 ============= */


undefined1 * usyms_lookup_addr(undefined4 param_1,uint param_2)

{
  int iVar1;
  int iVar2;
  uint *puVar3;
  int iVar4;
  char *__src;
  int iVar5;
  uint uVar6;
  int iVar7;
  uint *puVar8;
  int iVar9;
  int iVar10;
  int local_34;
  uint local_30;
  
  iVar1 = myfile_open_constprop_10();
  if (iVar1 != 0) {
    if (string_table != 0) {
      kfree();
      string_table = 0;
    }
    if (section_headers != 0) {
      kfree();
      section_headers = 0;
    }
    string_table_length = 0;
    iVar2 = get_elf_header_constprop_5(iVar1);
    if (iVar2 < 0) {
      filp_close(iVar1,0);
      return (undefined1 *)0x0;
    }
    if (is_32bit_elf == 0) {
      printk("\nIt is not 32 bit elf file\n");
    }
    else {
      iVar2 = get_32bit_section_headers_constprop_7(iVar1);
      if (-1 < iVar2) {
        if (string_table == 0) {
          get_string_table_part_0_constprop_13(iVar1);
        }
        if (Ehdr32._48_2_ != 0) {
          local_30 = 0;
          iVar2 = 0;
          local_34 = -1;
          iVar10 = 0;
          iVar9 = section_headers;
          do {
            if ((*(int *)(iVar9 + 4) == 0xb || *(int *)(iVar9 + 4) == 2) &&
               (puVar3 = (uint *)get_32bit_elf_symbols(iVar1,iVar9), puVar3 != (uint *)0x0)) {
              uVar6 = *(uint *)(iVar9 + 0x18);
              if (uVar6 == (ushort)Ehdr32._50_2_) {
                iVar7 = __aeabi_uidiv(*(undefined4 *)(iVar9 + 0x14),*(undefined4 *)(iVar9 + 0x24));
                local_30 = string_table_length;
                iVar2 = string_table;
                if (0 < iVar7) goto LAB_00011208;
              }
              else {
                if ((uVar6 < (ushort)Ehdr32._48_2_) &&
                   (iVar7 = section_headers + uVar6 * 0x28, *(int *)(iVar7 + 4) == 3)) {
                  iVar2 = get_data(iVar1,*(undefined4 *)(iVar7 + 0x10),*(undefined4 *)(iVar7 + 0x14)
                                   ,"string table");
                  if (iVar2 == 0) {
                    local_30 = 0;
                  }
                  else {
                    local_30 = *(uint *)(iVar7 + 0x14);
                  }
                }
                iVar7 = __aeabi_uidiv(*(undefined4 *)(iVar9 + 0x14),*(undefined4 *)(iVar9 + 0x24));
                iVar5 = string_table;
                if (0 < iVar7) {
LAB_00011208:
                  iVar5 = string_table;
                  iVar4 = 0;
                  puVar8 = puVar3;
                  do {
                    iVar4 = iVar4 + 1;
                    if ((((iVar2 != 0) && (((byte)puVar8[3] & 0xf) - 1 < 2)) &&
                        (puVar8[1] <= param_2)) && (param_2 < puVar8[1] + puVar8[2])) {
                      if (*puVar8 < local_30) {
                        __src = (char *)(iVar2 + *puVar8);
                      }
                      else {
                        __src = "<corrupt>";
                      }
                      local_34 = 0;
                      strncpy(sym_node + 0x14,__src,0x1f);
                      sym_node._12_4_ = puVar8[1];
                      sym_node._16_4_ = puVar8[2] + puVar8[1];
                      break;
                    }
                    puVar8 = puVar8 + 4;
                  } while (iVar4 < iVar7);
                }
                if (iVar2 != iVar5) {
                  kfree(iVar2);
                  iVar2 = 0;
                }
              }
              kfree(puVar3);
            }
            iVar10 = iVar10 + 1;
            iVar9 = iVar9 + 0x28;
          } while (iVar10 < (int)(uint)(ushort)Ehdr32._48_2_);
          if (local_34 != -1) {
            filp_close(iVar1,0);
            return sym_node;
          }
        }
      }
    }
    filp_close(iVar1,0);
    last_task_path[0] = 0;
  }
  return (undefined1 *)0x0;
}



/* ============= FUNCTION: dump_task_info @ 0001139c ============= */


void dump_task_info(undefined4 param_1)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  undefined1 *puVar5;
  int iVar6;
  uint uVar7;
  int iVar8;
  uint uVar9;
  uint uVar10;
  undefined4 local_80;
  undefined4 local_7c;
  undefined4 local_78;
  uint local_70 [20];
  
  iVar1 = find_task_by_vpid();
  if (iVar1 == 0) {
    return;
  }
  iVar2 = get_task_full_path_constprop_9();
  if (iVar2 < 1) {
    puVar5 = (undefined1 *)(iVar1 + 0x2d8);
  }
  else {
    puVar5 = &task_path;
  }
  printk("task %d , name %s stack %.8x ",param_1,puVar5,*(undefined4 *)(iVar1 + 4));
  if (*(int *)(iVar1 + 0x18c) == 0) {
    printk(&_LC28);
  }
  else {
    printk("pgd %.8x\n",*(undefined4 *)(*(int *)(iVar1 + 0x18c) + 0x24));
  }
  printk("affinity %x, nr_cpus_allowed %d\n",*(undefined4 *)(iVar1 + 0x160),
         *(undefined4 *)(iVar1 + 0x15c));
  iVar2 = *(int *)(iVar1 + 0x2d0);
  printk("cap_inheritable: %.8x\n",*(undefined4 *)(iVar2 + 0x28));
  printk("cap_permitted: %.8x\n",*(undefined4 *)(iVar2 + 0x30));
  printk("cap_effective: %.8x\n",*(undefined4 *)(iVar2 + 0x38));
  printk("cap_bset: %.8x\n",*(undefined4 *)(iVar2 + 0x40));
  iVar2 = *(int *)(iVar1 + 4);
  if (*(int *)(((uint)&local_80 & 0xffffe000) + 0xc) == iVar1) {
    printk("it is current task\n");
  }
  printk("thread at %.8x,kernel context:\n",iVar2);
  local_80 = *(undefined4 *)(iVar2 + 0x38);
  printk("e1 : %08x  e0 : %08x  pc : %08x  sp : %08x\n",*(undefined4 *)(iVar2 + 0x44),
         *(undefined4 *)(iVar2 + 0x40),*(undefined4 *)(iVar2 + 0x3c));
  local_80 = *(undefined4 *)(iVar2 + 0x28);
  printk("fp : %08x  sl : %08x  r9 : %08x  r8 : %08x\n",*(undefined4 *)(iVar2 + 0x34),
         *(undefined4 *)(iVar2 + 0x30),*(undefined4 *)(iVar2 + 0x2c));
  local_80 = *(undefined4 *)(iVar2 + 0x18);
  printk("r7 : %08x  r6 : %08x  r5 : %08x  r4 : %08x\n",*(undefined4 *)(iVar2 + 0x24),
         *(undefined4 *)(iVar2 + 0x20),*(undefined4 *)(iVar2 + 0x1c));
  printk("kernel backtrace:\n");
  show_stack(iVar1,0);
  if (*(int *)(iVar1 + 0x18c) != 0) {
    iVar6 = *(int *)(iVar1 + 4);
    iVar2 = 0;
    printk("user context:\n");
    local_80 = *(undefined4 *)(iVar6 + 0x1fe4);
    local_7c = *(undefined4 *)(iVar6 + 0x1fe0);
    local_78 = *(undefined4 *)(iVar6 + 0x1fdc);
    printk("pc : [<%08lx>]    lr : [<%08lx>]    psr: %08lx\nsp : %08lx  ip : %08lx  fp : %08lx\n",
           *(undefined4 *)(iVar6 + 0x1fec),*(undefined4 *)(iVar6 + 0x1fe8),
           *(undefined4 *)(iVar6 + 0x1ff0));
    printk("r10: %08lx  r9 : %08lx  r8 : %08lx\n",*(undefined4 *)(iVar6 + 0x1fd8),
           *(undefined4 *)(iVar6 + 0x1fd4),*(undefined4 *)(iVar6 + 0x1fd0));
    local_80 = *(undefined4 *)(iVar6 + 0x1fc0);
    printk("r7 : %08lx  r6 : %08lx  r5 : %08lx  r4 : %08lx\n",*(undefined4 *)(iVar6 + 0x1fcc),
           *(undefined4 *)(iVar6 + 0x1fc8),*(undefined4 *)(iVar6 + 0x1fc4));
    local_80 = *(undefined4 *)(iVar6 + 0x1fb0);
    printk("r3 : %08lx  r2 : %08lx  r1 : %08lx  r0 : %08lx\n",*(undefined4 *)(iVar6 + 0x1fbc),
           *(undefined4 *)(iVar6 + 0x1fb8),*(undefined4 *)(iVar6 + 0x1fb4));
    iVar6 = *(int *)(iVar1 + 0x18c);
    printk("start_code %08lx\n",*(undefined4 *)(iVar6 + 0x80));
    printk("end_code %08lx\n",*(undefined4 *)(iVar6 + 0x84));
    printk("start_data %08lx\n",*(undefined4 *)(iVar6 + 0x88));
    printk("end_data %08lx\n",*(undefined4 *)(iVar6 + 0x8c));
    printk("start_brk %08lx\n",*(undefined4 *)(iVar6 + 0x90));
    printk("brk %08lx\n",*(undefined4 *)(iVar6 + 0x94));
    printk("start_stack %08lx\n",*(undefined4 *)(iVar6 + 0x98));
    printk("arg_start %08lx\n",*(undefined4 *)(iVar6 + 0x9c));
    printk("arg_end %08lx\n",*(undefined4 *)(iVar6 + 0xa0));
    printk("env_start %08lx\n",*(undefined4 *)(iVar6 + 0xa4));
    printk("env_end %08lx\n",*(undefined4 *)(iVar6 + 0xa8));
    my_dump_vma(iVar1);
    uVar10 = *(uint *)(*(int *)(iVar1 + 0x18c) + 0x98);
    uVar7 = *(uint *)(*(int *)(iVar1 + 4) + 0x1fdc);
    do {
      uVar3 = user_va2pa(iVar1,uVar7);
      if (uVar3 == 0 || (uVar7 == 0 || uVar10 <= uVar7)) {
LAB_0001187c:
        if (iVar2 == 0) goto LAB_00011510;
        break;
      }
      uVar9 = uVar3 & 0xfffff000;
      if (uVar9 < 8) {
        iVar6 = user_va2pa(iVar1,uVar7 - 8);
        if (iVar6 == 0) goto LAB_0001187c;
        iVar6 = *(int *)(iVar6 + -0x80000000);
      }
      else {
        iVar6 = *(int *)(uVar3 + 0x7ffffff8);
      }
      if (uVar7 + 4 != iVar6) {
        printk("invalid stack\n");
        goto LAB_0001187c;
      }
      iVar6 = iVar2;
      if (iVar2 == 0) {
        iVar6 = 1;
        local_70[0] = *(int *)(uVar3 + 0x80000000) - 0xc;
      }
      if (uVar9 < 4) {
        iVar8 = user_va2pa(iVar1,uVar7 - 4);
        iVar2 = iVar6;
        if (iVar8 != 0) {
          local_70[iVar6] = *(uint *)(iVar8 + -0x80000000);
          goto LAB_000117f0;
        }
        goto LAB_0001187c;
      }
      if (0xb < uVar9) {
        uVar7 = *(uint *)(uVar3 + 0x7ffffff4);
      }
      local_70[iVar6] = *(uint *)(uVar3 + 0x7ffffffc);
      if (uVar9 < 0xc) {
LAB_000117f0:
        iVar2 = iVar6 + 1;
        iVar8 = user_va2pa(iVar1,uVar7 - 0xc);
        if (iVar8 == 0) goto LAB_0001187c;
        uVar7 = *(uint *)(iVar8 + -0x80000000);
      }
      iVar2 = iVar6 + 1;
    } while (iVar2 < 0x14);
    iVar8 = 0;
    mytree = 0;
    iVar6 = build_func_usyms(iVar1);
    do {
      uVar7 = local_70[iVar8];
      iVar4 = mytree;
      if (uVar7 == 0) break;
      while (iVar4 != 0) {
        if (uVar7 < *(uint *)(iVar4 + 0xc)) {
          iVar4 = *(int *)(iVar4 + 8);
        }
        else {
          if (uVar7 < *(uint *)(iVar4 + 0x10)) goto LAB_00011814;
          iVar4 = *(int *)(iVar4 + 4);
        }
      }
      iVar4 = get_usyms_lib(iVar1,uVar7);
      if (iVar4 == 0) {
        printk("%.8x\n",uVar7);
      }
      else {
LAB_00011814:
        printk("%.8x %s+%.8x\n",uVar7,iVar4 + 0x14,uVar7 - *(int *)(iVar4 + 0xc));
      }
      iVar8 = iVar8 + 1;
    } while (iVar8 < iVar2);
    if (iVar6 != 0) {
      kfree(iVar6);
    }
  }
LAB_00011510:
  printk("open file:\n");
  dump_task_fd(iVar1);
  return;
}



/* ============= FUNCTION: isint @ 000118b8 ============= */


undefined4 isint(byte *param_1,int param_2)

{
  uint uVar1;
  uint uVar2;
  
  if (param_1 == (byte *)0x0) {
    return 0;
  }
  uVar1 = (uint)*param_1;
  if (uVar1 == 0x2d) {
    uVar1 = (uint)param_1[1];
    param_1 = param_1 + 1;
  }
  if (uVar1 == 0x30) {
    if ((param_1[1] & 0xdf) == 0x42) {
      uVar1 = (uint)param_1[2];
      param_2 = 2;
      param_1 = param_1 + 2;
    }
    else if ((param_1[1] & 0xdf) == 0x58) {
      uVar1 = (uint)param_1[2];
      param_2 = 0x10;
      param_1 = param_1 + 2;
    }
    else {
      param_2 = 8;
    }
  }
  while( true ) {
    uVar2 = uVar1 - 0x30;
    if (((&_ctype)[uVar1] & 0x44) == 0) {
      return 0;
    }
    if (9 < uVar2) {
      uVar2 = uVar1 - 0x57;
      if ((5 < uVar1 - 0x61) && (uVar2 = 0, uVar1 - 0x41 < 6)) {
        uVar2 = uVar1 - 0x37;
      }
    }
    if (param_2 <= (int)uVar2) break;
    param_1 = param_1 + 1;
    uVar1 = (uint)*param_1;
    if (uVar1 == 0) {
      return 1;
    }
  }
  return 0;
}



/* ============= FUNCTION: set_syms_to_cache @ 0001197c ============= */


undefined1 *
set_syms_to_cache(char *param_1,undefined4 param_2,undefined4 *param_3,undefined4 *param_4)

{
  int iVar1;
  size_t sVar2;
  uint uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  undefined1 *puVar7;
  int extraout_r12;
  int iVar8;
  
  sVar2 = strlen(param_1);
  if (sVar2 < 0x3f) {
    uVar3 = full_name_hash(param_1,sVar2);
    iVar1 = (uVar3 & 0xff) * 0x60;
    puVar7 = &syms_cache + iVar1;
    *(undefined4 *)(&syms_cache + iVar1) = param_2;
    *(uint *)(&DAT_00014504 + iVar1) = uVar3;
    strncpy(&DAT_00014508 + iVar1,param_1,0x3f);
    iVar8 = extraout_r12;
    if (param_3 != (undefined4 *)0x0) {
      iVar8 = iVar1 + 0x48;
    }
    (&DAT_00014547)[iVar1] = 0;
    if (param_3 != (undefined4 *)0x0) {
      uVar4 = param_3[1];
      uVar5 = param_3[2];
      uVar6 = param_3[3];
      *(undefined4 *)(&syms_cache + iVar8) = *param_3;
      *(undefined4 *)(&DAT_00014504 + iVar8) = uVar4;
      *(undefined4 *)(&DAT_00014508 + iVar8) = uVar5;
      *(undefined4 *)(&DAT_0001450c + iVar8) = uVar6;
    }
    else {
      (&DAT_00014548)[iVar1] = 0;
    }
    if (param_4 != (undefined4 *)0x0) {
      uVar4 = param_4[1];
      iVar1 = (uVar3 & 0xff) * 0x60;
      *(undefined4 *)(&DAT_00014558 + iVar1) = *param_4;
      *(undefined4 *)(&DAT_0001455c + iVar1) = uVar4;
    }
  }
  else {
    puVar7 = (undefined1 *)0x0;
  }
  return puVar7;
}



/* ============= FUNCTION: shellReadProc @ 00011a3c ============= */


void shellReadProc(undefined4 param_1,undefined4 param_2)

{
  single_open(param_2,proc_shell_read,0);
  return;
}



/* ============= FUNCTION: check_shell_permit @ 00011a50 ============= */


undefined4 check_shell_permit(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  
  iVar2 = *(int *)(((uint)&stack0xfffffff0 & 0xffffe000) + 0xc);
  if (iVar2 != 0) {
    iVar3 = 6;
    do {
      iVar1 = strcmp((char *)(iVar2 + 0x2d8),"init");
      if (iVar1 == 0) {
        return 1;
      }
      iVar1 = strncmp("teln",(char *)(iVar2 + 0x2d8),4);
      if (iVar1 == 0) {
        return 0;
      }
      iVar1 = *(int *)(iVar2 + 0x200);
      if (iVar1 == iVar2) {
        return 1;
      }
      iVar3 = iVar3 + -1;
      if (iVar3 == 0) {
        return 0;
      }
      iVar2 = iVar1;
    } while (iVar1 != 0);
  }
  return 1;
}



/* ============= FUNCTION: shell_dump_sym_data @ 00011ad8 ============= */


void shell_dump_sym_data(uint *param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  byte *pbVar4;
  int iVar5;
  uint uVar6;
  uint *puVar7;
  uint uVar8;
  byte bStack_6d;
  uint local_6c [18];
  
  if (param_2 == 0) {
    if (data_cnt == 1) {
      DataSynchronizationBarrier(0xf);
      printk("sym %s is %d(0x%.2x)\n",sym,(byte)*param_1,(byte)*param_1);
      iVar5 = 1;
    }
    else {
      iVar5 = 1;
    }
  }
  else if (param_2 == 1) {
    if (data_cnt == 1) {
      DataSynchronizationBarrier(0xf);
      printk("sym %s is %d(0x%.4x)\n",sym,(ushort)*param_1,(ushort)*param_1);
      iVar5 = 1;
    }
    else {
      iVar5 = 2;
    }
  }
  else if (data_cnt == 1) {
    DataSynchronizationBarrier(0xf);
    printk("sym %s is %d(0x%.8x)\n",sym,*param_1,*param_1);
    iVar5 = 1;
  }
  else {
    iVar5 = 4;
  }
  if ((1 < (int)data_cnt) && (uVar6 = data_cnt & 0xffff, uVar6 != 0)) {
    uVar1 = __aeabi_idiv(0x10,iVar5);
    do {
      printk("%08x:",param_1);
      uVar8 = 0;
      puVar7 = param_1;
      if ((int)uVar6 <= (int)uVar1) {
        uVar1 = uVar6;
      }
      do {
        if (iVar5 == 4) {
          uVar3 = *puVar7;
          DataSynchronizationBarrier(0xf);
          local_6c[uVar8] = uVar3;
        }
        else if (iVar5 == 2) {
          uVar3 = (uint)(ushort)*puVar7;
          DataSynchronizationBarrier(0xf);
          *(ushort *)((int)local_6c + uVar8 * 2) = (ushort)*puVar7;
        }
        else {
          uVar3 = (uint)(byte)*puVar7;
          DataSynchronizationBarrier(0xf);
          *(byte *)((int)local_6c + uVar8) = (byte)*puVar7;
        }
        uVar8 = uVar8 + 1;
        printk(" %0*x",(int)(short)iVar5 << 1,uVar3);
        puVar7 = (uint *)((int)puVar7 + iVar5);
      } while (uVar8 != uVar1);
      iVar2 = uVar1 * iVar5;
      param_1 = (uint *)((int)param_1 + iVar5 * (uVar1 - 1) + iVar5);
      if (iVar2 < 1) {
        iVar2 = 0;
      }
      else {
        pbVar4 = &bStack_6d;
        do {
          pbVar4 = pbVar4 + 1;
          if ((((&_ctype)[*pbVar4] & 0x97) == 0) || ((*pbVar4 & 0x80) != 0)) {
            *pbVar4 = 0x2e;
          }
        } while (pbVar4 != (byte *)((int)local_6c + iVar2 + -1));
      }
      *(undefined1 *)((int)local_6c + iVar2) = 0;
      printk("    %s\n",local_6c);
      uVar6 = uVar6 - uVar1 & 0xffff;
    } while (uVar6 != 0);
  }
  return;
}



/* ============= FUNCTION: get_ksyms_address @ 00011d2c ============= */


uint get_ksyms_address(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int iVar1;
  uint uVar2;
  size_t sVar3;
  int iVar4;
  
  iVar1 = isint(param_1,0x10,param_3,param_4,param_4);
  if (iVar1 != 0) {
    uVar2 = simple_strtoul(param_1,0,0x10);
    if (uVar2 < 0xbf000001) {
      uVar2 = 0;
    }
    return uVar2;
  }
  sVar3 = strlen(param_1);
  uVar2 = full_name_hash(param_1,sVar3);
  iVar1 = (uVar2 & 0xff) * 0x60;
  if (((uVar2 == *(uint *)(&DAT_00014504 + iVar1)) &&
      (iVar4 = strcmp(param_1,&DAT_00014508 + iVar1), iVar1 != -0x14500 && iVar4 == 0)) &&
     (*(uint *)(&syms_cache + iVar1) != 0)) {
    return *(uint *)(&syms_cache + iVar1);
  }
  uVar2 = kallsyms_lookup_name(param_1);
  if (uVar2 == 0) {
    return 0;
  }
  set_syms_to_cache(param_1,uVar2,0,0);
  return uVar2;
}



/* ============= FUNCTION: shell_sym @ 00011e04 ============= */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void shell_sym(void)

{
  undefined4 uVar1;
  char *pcVar2;
  int iVar3;
  uint uVar4;
  code *pcVar5;
  undefined1 *puVar6;
  undefined *puVar7;
  char *pcVar8;
  char *pcVar9;
  int iVar10;
  undefined1 *local_138;
  undefined4 local_134;
  undefined1 *local_130;
  undefined1 auStack_128 [4];
  undefined1 auStack_124 [4];
  uint local_120;
  undefined1 *local_11c [5];
  undefined1 auStack_107 [227];
  
  pcVar8 = sym;
  if (sym_type == 3) {
    pcVar9 = (char *)0x0;
    uVar4 = 0;
  }
  else {
    pcVar2 = strchr(sym,0x3d);
    uVar1 = data_base;
    if (pcVar2 == (char *)0x0) {
      pcVar9 = (char *)0x0;
      uVar4 = 0;
    }
    else {
      pcVar9 = pcVar2 + 1;
      iVar3 = isint(pcVar9,data_base);
      if (iVar3 == 0) {
        printk("invalid data %s\n",pcVar8);
        return;
      }
      *pcVar2 = '\0';
      uVar4 = simple_strtoul(pcVar9,0,uVar1);
      pcVar8 = sym;
    }
  }
  pcVar5 = (code *)get_ksyms_address(pcVar8);
  if (pcVar5 == (code *)0x0) {
    printk("unknown symbol \"%s\"\n",sym);
  }
  else if (v2p == 0) {
    switch(sym_type) {
    case 0:
      if (pcVar9 == (char *)0x0) {
        shell_dump_sym_data(pcVar5,0);
        return;
      }
      printk("sym %s set to %d(0x%.2x)\n",sym,uVar4 & 0xff,uVar4 & 0xff);
      DataSynchronizationBarrier(0xe);
      if (_memcpy != (code *)0x0) {
        (*_memcpy)();
      }
      *pcVar5 = SUB41(uVar4,0);
      break;
    case 1:
      if (pcVar9 == (char *)0x0) {
        shell_dump_sym_data(pcVar5,1);
        return;
      }
      printk("sym %s set to %d(0x%.4x)\n",sym,uVar4 & 0xffff,uVar4 & 0xffff);
      DataSynchronizationBarrier(0xe);
      if (_memcpy != (code *)0x0) {
        (*_memcpy)();
      }
      *(short *)pcVar5 = (short)uVar4;
      break;
    case 2:
      if (pcVar9 == (char *)0x0) {
        shell_dump_sym_data(pcVar5,2);
        return;
      }
      printk("sym %s set to %d(0x%.8x)\n",sym,uVar4,uVar4);
      DataSynchronizationBarrier(0xe);
      if (_memcpy != (code *)0x0) {
        (*_memcpy)();
      }
      *(uint *)pcVar5 = uVar4;
      break;
    case 3:
      if (func_no_check == 0) {
        local_138 = auStack_107;
        iVar3 = kallsyms_lookup(pcVar5,&local_120,auStack_124,auStack_128);
        if (((iVar3 == 0) || (local_120 < 5)) || (((uint)pcVar5 & 3) != 0)) {
          printk("symbol %s is not a function\n",sym);
          return;
        }
      }
      if (func_param == (char *)0x0) {
switchD_00012170_default:
        printk("call func %s\n",sym);
        (*pcVar5)();
      }
      else {
        iVar3 = 0;
        pcVar8 = func_param;
        do {
          pcVar9 = strchr(pcVar8,0x2c);
          if (pcVar9 == (char *)0x0) {
            iVar10 = iVar3;
            if (*pcVar8 != '\0') {
              iVar10 = isint(pcVar8,0x10);
              if (iVar10 == 0) {
                iVar10 = iVar3 + 1;
                local_11c[iVar3] = pcVar8;
              }
              else {
                iVar10 = iVar3 + 1;
                puVar6 = (undefined1 *)simple_strtoul(pcVar8,0,0x10);
                local_11c[iVar3] = puVar6;
              }
            }
            switch(iVar10) {
            case 1:
              printk("call func %s,with p %x\n",sym,local_11c[0]);
              (*pcVar5)(local_11c[0]);
              return;
            case 2:
              printk("call func %s,with p %x,%x\n",sym,local_11c[0],local_11c[1]);
              (*pcVar5)(local_11c[0],local_11c[1]);
              return;
            case 3:
              local_138 = local_11c[2];
              printk("call func %s,with p %x,%x,%x\n",sym,local_11c[0],local_11c[1]);
              (*pcVar5)(local_11c[0],local_11c[1],local_11c[2]);
              return;
            case 4:
              local_138 = local_11c[2];
              local_134 = local_11c[3];
              printk("call func %s,with p %x,%x,%x,%x\n",sym,local_11c[0],local_11c[1]);
              (*pcVar5)(local_11c[0],local_11c[1],local_11c[2],local_11c[3]);
              return;
            case 5:
              goto switchD_00012170_caseD_5;
            default:
              goto switchD_00012170_default;
            }
          }
          *pcVar9 = '\0';
          iVar10 = isint(pcVar8,0x10);
          if (iVar10 == 0) {
            local_11c[iVar3] = pcVar8;
          }
          else {
            puVar6 = (undefined1 *)simple_strtoul(pcVar8,0,0x10);
            local_11c[iVar3] = puVar6;
          }
          iVar3 = iVar3 + 1;
          pcVar8 = pcVar9 + 1;
        } while (iVar3 != 5);
switchD_00012170_caseD_5:
        local_138 = local_11c[2];
        local_134 = local_11c[3];
        local_130 = local_11c[4];
        printk("call func %s,with p %x,%x,%x,%x,%x\n",sym,local_11c[0],local_11c[1]);
        local_138 = local_11c[4];
        (*pcVar5)(local_11c[0],local_11c[1],local_11c[2],local_11c[3]);
      }
      break;
    default:
      printk("sym %s address at 0x%.8x\n",sym,pcVar5);
      return;
    case 5:
      __print_symbol("address info: %s\n",pcVar5);
    }
  }
  else {
    puVar6 = (undefined1 *)((uint)pcVar5 >> 0x15);
    puVar7 = *(undefined **)(*(int *)(((uint)&local_138 & 0xffffe000) + 0xc) + 0x18c);
    if (puVar7 == (undefined *)0x0) {
      puVar7 = &init_mm;
    }
    iVar3 = *(int *)(puVar7 + 0x24);
    iVar10 = iVar3 + (int)puVar6 * 8;
    uVar4 = *(uint *)(iVar3 + (int)puVar6 * 8);
    local_138 = puVar6;
    printk("pgd 0x%x ,0x%x:pgd_val = 0x%x,index 0x%x\n",iVar3,iVar10,uVar4);
    if ((uVar4 & 3) == 2) {
      if (((uint)pcVar5 & 0x100000) != 0) {
        uVar4 = *(uint *)(iVar10 + 4);
      }
      printk("vaddr = %x, paddr = %x\n",pcVar5,(uVar4 & 0xfff00000) + ((uint)pcVar5 & 0xfffff));
      return;
    }
    printk("pud_val = 0x%x\n",*(undefined4 *)(iVar3 + (int)puVar6 * 8));
    if ((*(uint *)(iVar3 + (int)puVar6 * 8) & 2) != 0) {
      printk("pmd (bad)\n");
      return;
    }
    printk("pmd_val = 0x%x\n");
    uVar4 = (uint)((int)pcVar5 << 0xb) >> 0x17;
    iVar3 = (*(uint *)(iVar3 + (int)puVar6 * 8) & 0xfffff000) + 0x80000000;
    iVar10 = iVar3 + uVar4 * 4;
    printk("0x%x:pte_val = 0x%x *ppte=%08x\n",iVar10,*(undefined4 *)(iVar3 + uVar4 * 4),
           *(undefined4 *)(iVar10 + 0x800));
    if (*(uint *)(iVar10 + 0x800) == 0) {
      printk("not mapped in pte\n");
    }
    else {
      printk("vaddr = %x, paddr = %x\n",pcVar5,
             (*(uint *)(iVar10 + 0x800) & 0xfffff000) + ((uint)pcVar5 & 0xfff));
    }
  }
  return;
}



/* ============= FUNCTION: proc_shell_read @ 00012414 ============= */


void proc_shell_read(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = check_shell_permit();
  if (iVar1 == 0) {
    seq_printf(param_1,"NULL\n");
    return;
  }
  seq_printf(param_1,&_LC29,
             "Usage: echo [OPTIONS] > /proc/tm/shell \nexample -f sym p1,p2,p3 \n        sym=1, set sym to 1 \n        sym, get sym value \nOptions:\n  -b,         data is byte\n  -w,         data is word , 2 bytes\n  -l,         data is dword , 4 bytes\n  -f,         data is function with check\n  -F,         data is function ,no check\n  -c,         data counts\n  -a,         get sym address\n  -s,         translate address to sym name\n  -d,         data base is dec, default is hex\n  -p,         pid, dec mode\n  -P,         pid\'s full path\n  -t,         vaddr to paddr\n  -h,         help\n"
            );
  return;
}



/* ============= FUNCTION: user_va2pa @ 00012458 ============= */


int user_va2pa(int param_1,uint param_2)

{
  uint uVar1;
  int iVar2;
  
  uVar1 = *(uint *)((*(uint *)(*(int *)(*(int *)(param_1 + 0x18c) + 0x24) + (param_2 >> 0x15) * 8) &
                    0xfffff000) + ((param_2 << 0xb) >> 0x17) * 4 + 0x7ffff800);
  iVar2 = 0;
  if (uVar1 != 0) {
    iVar2 = (uVar1 & 0xfffff000) + (param_2 & 0xfff);
  }
  return iVar2;
}



/* ============= FUNCTION: check_user_addr @ 00012498 ============= */


bool check_user_addr(int param_1,uint param_2)

{
  uint *puVar1;
  
  puVar1 = (uint *)find_vma(*(undefined4 *)(param_1 + 0x18c));
  if (puVar1 == (uint *)0x0) {
    return false;
  }
  if (param_2 < *puVar1) {
    return false;
  }
  return param_2 < puVar1[1];
}



/* ============= FUNCTION: shellWriteProc @ 000124d8 ============= */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

uint shellWriteProc(undefined4 param_1,uint param_2,uint param_3)

{
  undefined4 uVar1;
  char *pcVar2;
  int iVar3;
  int iVar4;
  char *pcVar5;
  uint uVar6;
  int iVar7;
  size_t sVar8;
  int *piVar9;
  uint uVar10;
  uint uVar11;
  uint uVar12;
  uint *puVar13;
  char *pcVar14;
  char *pcVar15;
  undefined1 auStack_40 [4];
  char *local_3c;
  char *local_38;
  char *local_34;
  undefined2 local_30 [2];
  uint local_2c;
  
  uVar6 = param_3;
  if (0x7e < param_3) {
    uVar6 = 0x7f;
  }
  uVar12 = *(uint *)(((uint)auStack_40 & 0xffffe000) + 8);
  uVar10 = param_2 + uVar6;
  uVar11 = uVar10;
  if (!CARRY4(param_2,uVar6)) {
    uVar11 = uVar10 - (uVar12 + 1);
  }
  if (!CARRY4(param_2,uVar6) && uVar10 <= uVar12) {
    uVar12 = 0;
  }
  if (uVar12 == 0) {
    iVar3 = __copy_from_user(cmd_line,param_2,uVar6);
    if (iVar3 != 0) {
      return 0xfffffff2;
    }
  }
  else if (uVar6 != 0) {
    __memzero(cmd_line,uVar6,uVar11);
    return 0xfffffff2;
  }
  iVar3 = check_shell_permit();
  if (iVar3 == 0) {
    printk("operation forbid\n");
    return param_3;
  }
  cmd_line[uVar6] = 0;
  proc_get_cmd(cmd_line);
  iVar3 = proc_argc;
  if (proc_argc < 2) {
switchD_000125e0_caseD_47:
    printk(&_LC33,
           "Usage: echo [OPTIONS] > /proc/tm/shell \nexample -f sym p1,p2,p3 \n        sym=1, set sym to 1 \n        sym, get sym value \nOptions:\n  -b,         data is byte\n  -w,         data is word , 2 bytes\n  -l,         data is dword , 4 bytes\n  -f,         data is function with check\n  -F,         data is function ,no check\n  -c,         data counts\n  -a,         get sym address\n  -s,         translate address to sym name\n  -d,         data base is dec, default is hex\n  -p,         pid, dec mode\n  -P,         pid\'s full path\n  -t,         vaddr to paddr\n  -h,         help\n"
          );
    return param_3;
  }
  func_no_check = 0;
  sym = (char *)0x0;
  func_param = 0;
  pid_path = 0;
  v2p = 0;
  sym_type = 2;
  data_base = 0x10;
  sym_pid = -1;
  data_cnt = 1;
  optreset = 1;
  optind = 1;
  while (iVar4 = getopt(iVar3,(char **)proc_argv,"p:c:tFsadbwlfh?"), iVar7 = sym_pid, iVar4 != -1) {
    switch(iVar4) {
    case 0x46:
      func_no_check = 1;
      sym_type = 3;
      break;
    default:
      goto switchD_000125e0_caseD_47;
    case 0x61:
      sym_type = 4;
      break;
    case 0x62:
      sym_type = 0;
      break;
    case 99:
      uVar6 = simple_strtoul(optarg,0,data_base);
      data_cnt = uVar6 & 0xfff;
      break;
    case 100:
      data_base = 10;
      break;
    case 0x66:
      sym_type = 3;
      break;
    case 0x6c:
      sym_type = 2;
      break;
    case 0x70:
      sym_pid = simple_strtoul(optarg,0,10);
      break;
    case 0x73:
      sym_type = 5;
      break;
    case 0x74:
      v2p = 1;
      break;
    case 0x77:
      sym_type = 1;
    }
  }
  if (iVar3 <= optind) {
    printk("error: no symbol,%d/%d\n",optind,iVar3);
    return param_3;
  }
  pcVar14 = *(char **)(proc_argv + optind * 4);
  if (optind < iVar3 + -1) {
    func_param = *(undefined4 *)(proc_argv + optind * 4 + 4);
  }
  else {
    func_param = 0;
  }
  sym = pcVar14;
  if (sym_pid < 0) {
    shell_sym();
    return param_3;
  }
  if (sym_type == 3) {
    pcVar15 = (char *)0x0;
    uVar6 = 0;
  }
  else {
    pcVar5 = strchr(pcVar14,0x3d);
    uVar1 = data_base;
    if (pcVar5 == (char *)0x0) {
      pcVar15 = (char *)0x0;
      uVar6 = 0;
    }
    else {
      pcVar15 = pcVar5 + 1;
      iVar3 = isint(pcVar15,data_base);
      if (iVar3 == 0) {
        printk("invalid data %s\n",pcVar14);
        return param_3;
      }
      *pcVar5 = '\0';
      uVar6 = simple_strtoul(pcVar15,0,uVar1);
      pcVar14 = sym;
      iVar7 = sym_pid;
    }
  }
  iVar3 = find_task_by_vpid(iVar7);
  if ((iVar3 == 0) || (*(int *)(iVar3 + 0x18c) == 0)) goto LAB_00012aac;
  iVar7 = isint(pcVar14,0x10);
  if (iVar7 == 0) {
    local_3c = (char *)0x4500;
    sVar8 = strlen(pcVar14);
    uVar11 = full_name_hash(pcVar14,sVar8);
    local_3c = (char *)((uint)local_3c & 0xffff | 0x10000);
    iVar7 = (uVar11 & 0xff) * 0x60;
    pcVar5 = (char *)(iVar3 + 0x2d8U);
    if ((uVar11 == *(uint *)(local_3c + iVar7 + 4)) &&
       (local_38 = (char *)(iVar3 + 0x2d8U), local_34 = local_3c + iVar7,
       iVar4 = strcmp(pcVar14,local_3c + iVar7 + 8), pcVar2 = local_34, pcVar5 = local_38,
       iVar4 == 0)) {
      local_34 = local_38;
      local_38 = pcVar2;
      iVar4 = strcmp(pcVar5,local_3c + iVar7 + 0x48);
      pcVar5 = local_34;
      if (local_38 == (char *)0x0 || iVar4 != 0) goto LAB_00012924;
      iVar7 = *(int *)(local_3c + iVar7);
      pcVar14 = local_38;
LAB_000129f0:
      if ((*(short *)(pcVar14 + 0x58) == 1) && (sym_type != 4)) {
        if (*(int *)(pcVar14 + 0x5c) == 1) {
          sym_type = 0;
        }
        else {
          sym_type = 1;
          if (*(int *)(pcVar14 + 0x5c) != 2) {
            sym_type = 2;
          }
        }
      }
      else {
        sym_type = 4;
      }
    }
    else {
LAB_00012924:
      local_3c = pcVar5;
      piVar9 = (int *)usyms_lookup_name(iVar3,pcVar14,pid_path);
      if (piVar9 == (int *)0x0) goto LAB_00012aac;
      iVar7 = *piVar9;
      if (iVar7 != 0) {
        local_2c = (uint)*(ushort *)((int)piVar9 + 6);
        local_30[0] = (undefined2)piVar9[1];
        pcVar14 = (char *)set_syms_to_cache(pcVar14,iVar7,local_3c,local_30);
        if (pcVar14 != (char *)0x0) goto LAB_000129f0;
      }
    }
    iVar3 = user_va2pa(iVar3,iVar7);
  }
  else {
    iVar7 = simple_strtoul(pcVar14,0,0x10);
    iVar4 = check_user_addr(iVar3,iVar7);
    if (iVar4 == 0) goto LAB_00012aac;
    iVar3 = user_va2pa(iVar3,iVar7);
    if (iVar3 == 0) {
      printk("va %.8lx no pa\n",iVar7);
      goto LAB_00012aac;
    }
  }
  if (iVar7 != 0) {
    puVar13 = (uint *)(iVar3 + -0x80000000);
    if (sym_type == 1) {
      if (pcVar15 != (char *)0x0) {
        printk("sym %s set to %d(0x%.4x)\n",sym,uVar6 & 0xffff,uVar6 & 0xffff);
        DataSynchronizationBarrier(0xe);
        if (_memcpy != (code *)0x0) {
          (*_memcpy)();
        }
        *(short *)puVar13 = (short)uVar6;
        return param_3;
      }
    }
    else {
      if (sym_type != 2) {
        if (sym_type != 0) {
          printk("sym %s va 0x%.8x pa 0x%.8x\n",sym);
          return param_3;
        }
        if (pcVar15 == (char *)0x0) {
          shell_dump_sym_data(puVar13,0);
          return param_3;
        }
        printk("sym %s set to %d(0x%.2x)\n",sym,uVar6 & 0xff,uVar6 & 0xff);
        DataSynchronizationBarrier(0xe);
        if (_memcpy != (code *)0x0) {
          (*_memcpy)();
        }
        *(char *)puVar13 = (char)uVar6;
        return param_3;
      }
      if (pcVar15 != (char *)0x0) {
        printk("sym %s set to %d(0x%.8x)\n",sym,uVar6,uVar6);
        DataSynchronizationBarrier(0xe);
        if (_memcpy != (code *)0x0) {
          (*_memcpy)();
        }
        *puVar13 = uVar6;
        return param_3;
      }
    }
    shell_dump_sym_data(puVar13);
    return param_3;
  }
LAB_00012aac:
  printk("pid 0x%x unknown symbol \"%s\"\n",sym_pid,sym);
  return param_3;
}



/* ============= FUNCTION: create_shell_proc @ 00012bec ============= */


int create_shell_proc(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = proc_create_data("shell",0x124,param_1,proc_shell_operations,0);
  return -(uint)(iVar1 == 0);
}



/* ============= FUNCTION: proc_parse_mac @ 00012c2c ============= */


undefined4 proc_parse_mac(char *param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 *puVar3;
  undefined1 *puVar4;
  undefined4 uStack_20;
  undefined1 auStack_1c [4];
  undefined1 auStack_18 [4];
  undefined1 auStack_14 [4];
  undefined1 auStack_10 [4];
  undefined1 auStack_c [4];
  
  iVar1 = sscanf(param_1,"%x:%x:%x:%x:%x:%x",&uStack_20,auStack_1c,auStack_18,auStack_14,auStack_10,
                 auStack_c);
  if (iVar1 == 6) {
    puVar4 = (undefined1 *)(param_2 + -1);
    puVar3 = &uStack_20;
    do {
      puVar4 = puVar4 + 1;
      *puVar4 = (char)*puVar3;
      puVar3 = puVar3 + 1;
    } while (puVar4 != (undefined1 *)(param_2 + 5));
    uVar2 = 0;
  }
  else {
    uVar2 = 0xffffffff;
  }
  return uVar2;
}



/* ============= FUNCTION: proc_parse_ip @ 00012ca4 ============= */


undefined4 proc_parse_ip(char *param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 *puVar3;
  undefined1 *puVar4;
  undefined4 uStack_18;
  undefined1 auStack_14 [4];
  undefined1 auStack_10 [4];
  undefined1 auStack_c [4];
  
  iVar1 = sscanf(param_1,"%d.%d.%d.%d",&uStack_18,auStack_14,auStack_10,auStack_c);
  if (iVar1 == 4) {
    puVar4 = (undefined1 *)(param_2 + -1);
    puVar3 = &uStack_18;
    do {
      puVar4 = puVar4 + 1;
      *puVar4 = (char)*puVar3;
      puVar3 = puVar3 + 1;
    } while (puVar4 != (undefined1 *)(param_2 + 3));
    uVar2 = 0;
  }
  else {
    uVar2 = 0xffffffff;
  }
  return uVar2;
}



/* ============= FUNCTION: proc_get_cmd @ 00012d0c ============= */


void proc_get_cmd(byte *param_1)

{
  byte bVar1;
  size_t sVar2;
  char *pcVar3;
  byte *pbVar4;
  uint uVar6;
  int iVar7;
  undefined1 *puVar8;
  bool bVar9;
  byte *pbVar5;
  
  proc_argc = 1;
  if (param_1 == (byte *)0x0) {
    return;
  }
  sVar2 = strlen((char *)param_1);
  if (0 < (int)sVar2) {
    pbVar5 = param_1;
    do {
      pbVar4 = pbVar5 + 1;
      bVar1 = *pbVar5;
      bVar9 = 0xc < bVar1;
      if (bVar1 != 0xd) {
        bVar9 = bVar1 != 9;
      }
      if (!bVar9 || (bVar1 == 0xd || bVar1 == 10)) {
        *pbVar5 = 0x20;
      }
      pbVar5 = pbVar4;
    } while (pbVar4 != param_1 + sVar2);
  }
  puVar8 = proc_argv;
  iVar7 = 1;
  do {
    uVar6 = (uint)*param_1;
    bVar1 = (&_ctype)[uVar6];
    while ((bVar1 & 0x20) != 0) {
      param_1 = param_1 + 1;
      uVar6 = (uint)*param_1;
      bVar1 = (&_ctype)[uVar6];
    }
    if (uVar6 == 0) {
      proc_argc = iVar7;
      return;
    }
    puVar8 = (undefined1 *)((int)puVar8 + 4);
    *(byte **)puVar8 = param_1;
    pcVar3 = strchr((char *)param_1,0x20);
    iVar7 = iVar7 + 1;
    if (pcVar3 == (char *)0x0) {
      proc_argc = iVar7;
      return;
    }
    *pcVar3 = '\0';
    param_1 = (byte *)(pcVar3 + 1);
  } while (iVar7 != 0x1e);
  proc_argc = iVar7;
  return;
}



/* ============= FUNCTION: getopt @ 00012dd0 ============= */


int getopt(int ___argc,char **___argv,char *__shortopts)

{
  char *pcVar1;
  byte *pbVar2;
  uint __c;
  
  if ((optreset == 0) && (__c = (uint)*place_17109, __c != 0)) {
    pbVar2 = place_17109 + 1;
LAB_00012e1c:
    place_17109 = pbVar2;
    optopt = __c;
    if (__c == 0x3a) goto LAB_00012e24;
  }
  else {
    optreset = 0;
    pcVar1 = ___argv[optind];
    if ((___argc <= optind) || (*pcVar1 != '-')) {
      place_17109 = &_LC2;
      optreset = 0;
      return -1;
    }
    __c = (uint)(byte)pcVar1[1];
    pbVar2 = (byte *)(pcVar1 + 2);
    optopt = __c;
    if (__c == 0x2d) {
      place_17109 = pbVar2;
      if (pcVar1[2] == '\0') {
        place_17109 = &_LC2;
        optind = optind + 1;
        optreset = 0;
        return -1;
      }
    }
    else {
      if (__c != 0) goto LAB_00012e1c;
      pbVar2 = &_LC2;
      place_17109 = &_LC2;
      pcVar1 = strchr(__shortopts,0x2d);
      if (pcVar1 == (char *)0x0) {
        return -1;
      }
      optopt = 0x2d;
    }
    __c = 0x2d;
  }
  pcVar1 = strchr(__shortopts,__c);
  if (pcVar1 != (char *)0x0) {
    if (pcVar1[1] == ':') {
      if (*pbVar2 == 0) {
        optind = optind + 1;
        if (___argc <= optind) {
          place_17109 = &_LC2;
          if (*__shortopts != ':') {
            printk("option requires an argument -- %c\n",__c);
            return 0x3f;
          }
          return 0x3a;
        }
        pbVar2 = (byte *)___argv[optind];
      }
      optarg = pbVar2;
      optind = optind + 1;
      place_17109 = &_LC2;
    }
    else {
      optarg = (byte *)0x0;
      if (*pbVar2 == 0) {
        optind = optind + 1;
      }
    }
    return optopt;
  }
LAB_00012e24:
  if (*pbVar2 == 0) {
    optind = optind + 1;
  }
  if (*__shortopts != ':') {
    printk("unknown option -- %c\n",__c);
  }
  return 0x3f;
}



/* ============= FUNCTION: tm_proc_init @ 00013004 ============= */


undefined4 tm_proc_init(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  tm_proc_root = proc_mkdir(&_LC5,0,param_3,param_4,param_4);
  if (tm_proc_root != 0) {
    create_shell_proc();
    return 0;
  }
  printk("proc_mkdir tm failed");
  return 0xffffffff;
}



/* ============= FUNCTION: dump_task_fd @ 0001304c ============= */


void dump_task_fd(int param_1)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  uint *puVar6;
  int iVar7;
  undefined1 auStack_118 [256];
  
  puVar6 = *(uint **)(*(int *)(param_1 + 0x310) + 4);
  for (iVar7 = 0; uVar5 = iVar7 << 3, uVar5 < *puVar6; iVar7 = iVar7 + 4) {
    iVar4 = iVar7 << 5;
    uVar3 = *(uint *)(puVar6[3] + iVar7);
    while (uVar3 != 0) {
      uVar1 = uVar3 & 1;
      uVar3 = uVar3 >> 1;
      if (uVar1 != 0) {
        if ((*(int *)(puVar6[1] + iVar4) != 0) &&
           (iVar2 = d_path(*(int *)(puVar6[1] + iVar4) + 8,auStack_118,0x100), iVar2 != 0)) {
          printk("fd %d : %s\n",uVar5);
        }
      }
      uVar5 = uVar5 + 1;
      iVar4 = iVar4 + 4;
    }
  }
  return;
}



/* ============= FUNCTION: my_dump_vma @ 000130e4 ============= */


void my_dump_vma(int param_1)

{
  bool bVar1;
  int iVar2;
  char *pcVar3;
  uint uVar4;
  undefined4 uVar5;
  uint uVar6;
  undefined4 *puVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  undefined4 uVar11;
  undefined4 uVar12;
  undefined4 uVar13;
  char acStack_120 [260];
  
  iVar9 = *(int *)(param_1 + 0x18c);
  iVar8 = *(int *)(param_1 + 4);
  iVar2 = rb_last(iVar9 + 4);
  if (iVar2 == 0) {
    printk("rb_node is NULL,%s\n","my_dump_vma");
  }
  else if (iVar2 == 0x10) {
    printk("vma is NULL\n");
  }
  else {
    uVar4 = *(uint *)(iVar8 + 0x1fe4);
    if (uVar4 < *(uint *)(iVar2 + -0x10)) {
      bVar1 = false;
    }
    else if (uVar4 < *(uint *)(iVar2 + -0xc)) {
      bVar1 = true;
    }
    else {
      bVar1 = false;
    }
    for (iVar2 = rb_first(iVar9 + 4); iVar2 != 0; iVar2 = rb_next(iVar2)) {
      uVar4 = *(uint *)(iVar2 + 0x18);
      iVar10 = *(int *)(iVar2 + 0x40);
      if ((uVar4 & 1) == 0) {
        uVar5 = 0x2d;
      }
      else {
        uVar5 = 0x72;
      }
      if ((uVar4 & 2) == 0) {
        uVar12 = 0x2d;
      }
      else {
        uVar12 = 0x77;
      }
      if ((uVar4 & 4) == 0) {
        uVar13 = 0x2d;
      }
      else {
        uVar13 = 0x78;
      }
      if ((uVar4 & 0x80) == 0) {
        uVar11 = 0x70;
      }
      else {
        uVar11 = 0x73;
      }
      printk("vma : %.8lx-%.8lx %c%c%c%c ",*(undefined4 *)(iVar2 + -0x10),
             *(undefined4 *)(iVar2 + -0xc),uVar5,uVar12,uVar13,uVar11);
      if (iVar10 == 0) {
        uVar4 = *(uint *)(iVar2 + -0x10);
        if ((*(uint *)(iVar9 + 0x94) < uVar4) || (*(uint *)(iVar2 + -0xc) < *(uint *)(iVar9 + 0x90))
           ) {
          uVar6 = *(uint *)(iVar9 + 0x98);
          if ((uVar6 < uVar4) || (*(uint *)(iVar2 + -0xc) < uVar6)) {
            if (((uVar6 ^ uVar4) & 0xf0000000) != 0) goto LAB_00013328;
            uVar6 = *(uint *)(iVar8 + 0x1fe4);
            if ((uVar6 < uVar4) || (*(uint *)(iVar2 + -0xc) <= uVar6)) {
              iVar10 = param_1;
              if (!bVar1) {
                iVar10 = *(int *)(param_1 + 0x200);
              }
              for (puVar7 = *(undefined4 **)(iVar10 + 0x208);
                  puVar7 != (undefined4 *)(iVar10 + 0x208); puVar7 = (undefined4 *)*puVar7) {
                if ((uVar4 <= *(uint *)(puVar7[-0x83] + 0x1fe4)) &&
                   (*(uint *)(puVar7[-0x83] + 0x1fe4) < *(uint *)(iVar2 + -0xc))) {
                  if ((int)puVar7[-6] < 0) {
                    pcVar3 = "[stack:child]";
                  }
                  else {
                    sprintf(acStack_120,"[stack:%d]");
                    pcVar3 = acStack_120;
                  }
                  goto LAB_00013330;
                }
              }
              pcVar3 = "[stack:child]";
            }
            else {
              sprintf(acStack_120,"[stack:%d]",*(undefined4 *)(param_1 + 0x1f8));
              pcVar3 = acStack_120;
            }
          }
          else {
            if (bVar1) {
              uVar5 = *(undefined4 *)(param_1 + 0x1f8);
            }
            else {
              uVar5 = *(undefined4 *)(*(int *)(param_1 + 0x200) + 0x1f8);
            }
            sprintf(acStack_120,"[stack:parent %d]",uVar5);
            pcVar3 = acStack_120;
          }
        }
        else {
          pcVar3 = "[heap]";
        }
      }
      else {
        pcVar3 = (char *)d_path(iVar10 + 8,acStack_120,0x100);
        if (pcVar3 == (char *)0x0) {
LAB_00013328:
          pcVar3 = "";
        }
      }
LAB_00013330:
      printk(&_LC9,pcVar3);
    }
  }
  return;
}



/* ============= FUNCTION: get_usyms_lib @ 00013364 ============= */


int get_usyms_lib(int param_1,uint param_2)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  undefined1 auStack_110 [260];
  
  iVar1 = rb_first(*(int *)(param_1 + 0x18c) + 4);
  while( true ) {
    if (iVar1 == 0) {
      return 0;
    }
    if ((*(uint *)(iVar1 + -0x10) <= param_2) && (param_2 < *(uint *)(iVar1 + -0xc))) break;
    iVar1 = rb_next(iVar1);
  }
  uVar3 = ((*(uint *)(iVar1 + 0x18) ^ 4) << 0x1d) >> 0x1f;
  if (*(int *)(iVar1 + 0x40) == 0) {
    uVar3 = 1;
  }
  if (uVar3 != 0) {
    return 0;
  }
  iVar2 = d_path(*(int *)(iVar1 + 0x40) + 8,auStack_110,0x100);
  if (iVar2 == 0) {
    return 0;
  }
  iVar2 = usyms_lookup_addr(iVar2,param_2 - *(int *)(iVar1 + -0x10));
  if (iVar2 != 0) {
    *(int *)(iVar2 + 0xc) = *(int *)(iVar2 + 0xc) + *(int *)(iVar1 + -0x10);
    return iVar2;
  }
  return 0;
}



/* ============= FUNCTION: init_module @ 00013428 ============= */


undefined4 init_module(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  tm_proc_root = proc_mkdir(&_LC5,0,param_3,param_4,param_4);
  if (tm_proc_root != 0) {
    create_shell_proc();
    return 0;
  }
  printk("proc_mkdir tm failed");
  return 0xffffffff;
}



/* ============= FUNCTION: filp_open @ 0001b000 ============= */


/* WARNING: Control flow encountered bad instruction data */

void filp_open(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: rb_last @ 0001b008 ============= */


/* WARNING: Control flow encountered bad instruction data */

void rb_last(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kallsyms_lookup @ 0001b00c ============= */


/* WARNING: Control flow encountered bad instruction data */

void kallsyms_lookup(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: rb_next @ 0001b014 ============= */


/* WARNING: Control flow encountered bad instruction data */

void rb_next(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: memcpy @ 0001b018 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memcpy(void *__dest,void *__src,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kfree @ 0001b01c ============= */


/* WARNING: Control flow encountered bad instruction data */

void kfree(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: proc_create_data @ 0001b024 ============= */


/* WARNING: Control flow encountered bad instruction data */

void proc_create_data(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: free_pages @ 0001b028 ============= */


/* WARNING: Control flow encountered bad instruction data */

void free_pages(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: rb_insert_color @ 0001b02c ============= */


/* WARNING: Control flow encountered bad instruction data */

void rb_insert_color(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: full_name_hash @ 0001b030 ============= */


/* WARNING: Control flow encountered bad instruction data */

void full_name_hash(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __get_free_pages @ 0001b034 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __get_free_pages(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: find_vma @ 0001b038 ============= */


/* WARNING: Control flow encountered bad instruction data */

void find_vma(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kallsyms_lookup_name @ 0001b040 ============= */


/* WARNING: Control flow encountered bad instruction data */

void kallsyms_lookup_name(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strncmp @ 0001b044 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int strncmp(char *__s1,char *__s2,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strncpy @ 0001b048 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

char * strncpy(char *__dest,char *__src,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: sscanf @ 0001b04c ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int sscanf(char *__s,char *__format,...)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: printk @ 0001b050 ============= */


/* WARNING: Control flow encountered bad instruction data */

void printk(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kmalloc_order @ 0001b054 ============= */


/* WARNING: Control flow encountered bad instruction data */

void kmalloc_order(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __print_symbol @ 0001b05c ============= */


/* WARNING: Control flow encountered bad instruction data */

void __print_symbol(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: proc_mkdir @ 0001b060 ============= */


/* WARNING: Control flow encountered bad instruction data */

void proc_mkdir(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __memzero @ 0001b064 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __memzero(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: rb_first @ 0001b06c ============= */


/* WARNING: Control flow encountered bad instruction data */

void rb_first(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strcmp @ 0001b070 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int strcmp(char *__s1,char *__s2)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: sprintf @ 0001b078 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int sprintf(char *__s,char *__format,...)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: filp_close @ 0001b07c ============= */


/* WARNING: Control flow encountered bad instruction data */

void filp_close(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: seq_printf @ 0001b080 ============= */


/* WARNING: Control flow encountered bad instruction data */

void seq_printf(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: simple_strtoul @ 0001b084 ============= */


/* WARNING: Control flow encountered bad instruction data */

void simple_strtoul(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strlen @ 0001b090 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

size_t strlen(char *__s)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: single_open @ 0001b098 ============= */


/* WARNING: Control flow encountered bad instruction data */

void single_open(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strchr @ 0001b09c ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

char * strchr(char *__s,int __c)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __copy_from_user @ 0001b0a0 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __copy_from_user(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: show_stack @ 0001b0a4 ============= */


/* WARNING: Control flow encountered bad instruction data */

void show_stack(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __kmalloc @ 0001b0a8 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __kmalloc(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: d_path @ 0001b0ac ============= */


/* WARNING: Control flow encountered bad instruction data */

void d_path(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: find_task_by_vpid @ 0001b0b0 ============= */


/* WARNING: Control flow encountered bad instruction data */

void find_task_by_vpid(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



