/* Concatenated Ghidra decomp of patch.ko */
/* 15 functions, generated by dump_all_concat.py */

/* ============= FUNCTION: patch_function @ 00010000 ============= */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
patch_function(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  undefined4 uVar1;
  undefined4 uVar2;
  
  invalid_l1_inst(param_1,0x14,param_3,param_4,param_4);
  uVar2 = uRam00010254;
  uVar1 = _hack_function0;
  param_1[4] = param_2;
  *param_1 = uVar1;
  param_1[1] = uVar2;
  param_1[2] = 0xe12fff34;
  param_1[3] = 0xe8bd8010;
  clean_l1_dcache(param_1,0x14);
  return 0;
}



/* ============= FUNCTION: patch_function_name @ 00010054 ============= */


undefined4 patch_function_name(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = get_ksyms_address();
  if (iVar1 != 0) {
    uVar2 = patch_function(iVar1,param_2);
    return uVar2;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: patch_pci_read_u32 @ 0001007c ============= */


undefined4 patch_pci_read_u32(undefined4 param_1,undefined4 *param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  
  pci_read_coming = 1;
  uVar1 = _raw_spin_lock_irqsave(l2_lock);
  uVar2 = *param_2;
  pci_read_coming = 0;
  _raw_spin_unlock_irqrestore(l2_lock,uVar1);
  return uVar2;
}



/* ============= FUNCTION: patch_op_pa_range @ 000100bc ============= */


void patch_op_pa_range(uint *param_1,uint param_2,uint param_3)

{
  undefined4 uVar1;
  uint uVar2;
  
  uVar1 = _raw_spin_lock_irqsave(l2_lock);
  if (param_2 < param_3) {
    do {
      uVar2 = param_3 - param_2;
      if (l2_lock_size < uVar2) {
        uVar2 = l2_lock_size;
      }
      uVar2 = param_2 + uVar2;
      do {
        if (uVar2 <= param_2) break;
        *param_1 = param_2;
        param_2 = param_2 + 0x20;
      } while (pci_read_coming == 0);
      if (param_3 <= param_2) break;
      _raw_spin_unlock_irqrestore(l2_lock,uVar1);
      uVar1 = _raw_spin_lock_irqsave(l2_lock);
    } while( true );
  }
  _raw_spin_unlock_irqrestore(l2_lock,uVar1);
  return;
}



/* ============= FUNCTION: l2x0_patch @ 00010150 ============= */


undefined4 l2x0_patch(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = get_ksyms_address("l2x0_lock");
  if (iVar1 == 0) {
    uVar2 = 0xffffffff;
  }
  else {
    l2_lock = iVar1;
    iVar1 = get_ksyms_address("__l2c210_op_pa_range");
    if (iVar1 != 0) {
      uVar2 = _raw_spin_lock_irqsave(l2_lock);
      patch_function(&fixed_pci_read_u32,patch_pci_read_u32);
      patch_function(iVar1,patch_op_pa_range);
      _raw_spin_unlock_irqrestore(l2_lock,uVar2);
      return 0;
    }
    uVar2 = 0xfffffffe;
  }
  printk("patch module%d failed %d\n",0,uVar2);
  return 0;
}



/* ============= FUNCTION: invalid_l1_inst @ 000101f0 ============= */


undefined4 invalid_l1_inst(uint param_1,int param_2)

{
  uint uVar1;
  undefined4 in_cr1;
  undefined4 in_cr7;
  
  uVar1 = param_1 & 0xffffffe0;
  DataSynchronizationBarrier(0xf);
  do {
    coproc_moveto_Invalidate_Instruction_Cache_by_MVA(uVar1);
    uVar1 = uVar1 + 0x20;
  } while (uVar1 < param_2 + param_1);
  coprocessor_moveto(0xf,0,6,0,in_cr7,in_cr1);
  DataSynchronizationBarrier(0xf);
  InstructionSynchronizationBarrier(0xf);
  return 0;
}



/* ============= FUNCTION: invalid_icache_all @ 00010220 ============= */


undefined4 invalid_icache_all(void)

{
  undefined4 in_cr1;
  undefined4 in_cr7;
  
  coprocessor_moveto(0xf,0,0,0,in_cr7,in_cr1);
  return 0;
}



/* ============= FUNCTION: clean_l1_dcache @ 0001022c ============= */


void clean_l1_dcache(uint param_1,int param_2)

{
  uint uVar1;
  
  uVar1 = param_1 & 0xffffffe0;
  DataSynchronizationBarrier(0xf);
  do {
    coproc_moveto_Clean_Data_Cache_by_MVA(uVar1);
    uVar1 = uVar1 + 0x20;
  } while (uVar1 < param_2 + param_1);
  DataSynchronizationBarrier(0xf);
  return;
}



/* ============= FUNCTION: hack_function0 @ 00010250 ============= */


void hack_function0(void)

{
  (*(code *)&SUB_e320f000)();
  return;
}



/* ============= FUNCTION: init_module @ 00010268 ============= */


undefined4 init_module(void)

{
  l2x0_patch();
  invalid_icache_all();
  return 0;
}



/* ============= FUNCTION: cleanup_module @ 0001027c ============= */


void cleanup_module(void)

{
  printk("bug!!!,patch module ,exit\n");
  return;
}



/* ============= FUNCTION: _raw_spin_lock_irqsave @ 00011004 ============= */


/* WARNING: Control flow encountered bad instruction data */

void _raw_spin_lock_irqsave(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: printk @ 0001100c ============= */


/* WARNING: Control flow encountered bad instruction data */

void printk(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: _raw_spin_unlock_irqrestore @ 00011010 ============= */


/* WARNING: Control flow encountered bad instruction data */

void _raw_spin_unlock_irqrestore(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: get_ksyms_address @ 00011018 ============= */


/* WARNING: Control flow encountered bad instruction data */

void get_ksyms_address(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



