/* Concatenated Ghidra decomp of kudp.ko */
/* 45 functions, generated by dump_all_concat.py */

/* ============= FUNCTION: udp_modify_media @ 00010000 ============= */


undefined4 udp_modify_media(void)

{
  return 0;
}



/* ============= FUNCTION: set_kudp_trace @ 00010008 ============= */


void set_kudp_trace(undefined1 param_1)

{
  bKudp_Debug_Trace = param_1;
  return;
}



/* ============= FUNCTION: udp_rtptrace_start @ 00010018 ============= */


void udp_rtptrace_start(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  uint uVar1;
  
  if (trace_thread._0_4_ == 0) {
    uVar1 = kthread_create_on_node(trace_func,0,0xffffffff,"TRACE");
    if (uVar1 < 0xfffff001) {
      wake_up_process();
    }
    trace_thread._0_4_ = uVar1;
    if (uVar1 == 0) {
      return;
    }
  }
  TraceRemoteIP = param_1;
  TraceLocalIP = param_2;
  TraceMask = param_3;
  return;
}



/* ============= FUNCTION: udp_rtptrace_close @ 0001008c ============= */


void udp_rtptrace_close(void)

{
  if (trace_thread._0_4_ != 0) {
    trace_thread._8_4_ = 1;
    while (trace_thread._4_4_ == 1) {
      complete(ComTrace);
      msleep(10);
    }
  }
  trace_thread._0_4_ = 0;
  TraceMask = 0xf;
  TraceRemoteIP = 0;
  TraceLocalIP = 0;
  return;
}



/* ============= FUNCTION: SendUdpPacket @ 000100fc ============= */


undefined4
SendUdpPacket(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
             undefined4 param_5)

{
  undefined4 uVar1;
  undefined4 local_3c;
  undefined4 local_38;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_c;
  
  local_38 = param_5;
  local_2c = 0;
  local_28 = 0;
  local_24 = 0;
  local_20 = 0;
  local_1c = 0;
  local_18 = 0;
  local_14 = 0;
  local_c = 0;
  local_10 = 0x4040;
  if (param_1 == 0) {
    uVar1 = 0xffffffff;
  }
  else {
    local_3c = param_4;
    local_34 = param_2;
    local_30 = param_3;
    uVar1 = kernel_sendmsg(param_1,&local_34,&local_3c,1,param_5);
  }
  return uVar1;
}



/* ============= FUNCTION: trace_func @ 00010170 ============= */


void trace_func(undefined4 param_1,int param_2)

{
  int iVar1;
  int iVar2;
  undefined2 uVar3;
  int extraout_r1;
  int extraout_r1_00;
  
  trace_thread._4_4_ = 1;
  trace_thread._8_4_ = 0;
  TraceInSn = 0;
  TraceOutSn = 0;
  while (trace_thread._8_4_ == 0) {
    wait_for_completion(ComTrace,param_2);
    iVar1 = TraceOutSn * 0x408;
    param_2 = extraout_r1;
    if ((byte)TraceData[iVar1] < 4) {
      iVar2 = (uint)(byte)TraceData[iVar1] * 0xf0;
      param_2 = iVar2 + 0x1e610;
      if (*(int *)(Medias + iVar2 + 0x90) != 0) {
        if (TraceData[iVar1 + 1] == '\0') {
          param_2 = iVar2 + 0x1e600;
          uVar3 = *(undefined2 *)(TraceData + iVar1 + 2);
        }
        else {
          uVar3 = *(undefined2 *)(TraceData + iVar1 + 2);
        }
        SendUdpPacket(*(int *)(Medias + iVar2 + 0x90),param_2,0x10,iVar1 + 0x11c08,uVar3);
        param_2 = extraout_r1_00;
      }
      TraceOutSn = TraceOutSn + 1;
      if (TraceOutSn == 0x32) {
        param_2 = 0;
        TraceOutSn = 0;
      }
    }
  }
  trace_thread._4_4_ = 0;
  return;
}



/* ============= FUNCTION: TRACE1 @ 0001027c ============= */


undefined4 TRACE1(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  size_t sVar1;
  undefined2 local_40 [2];
  undefined4 local_3c;
  undefined2 local_30;
  undefined2 local_2e;
  uint local_2c;
  undefined4 uStack_c;
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  if ((UdpWatchFlag != 0) && (UdpWatchRemoteIP != 0)) {
    udpwatchsn_48024 = udpwatchsn_48024 + '\x01';
    uStack_c = param_2;
    uStack_8 = param_3;
    uStack_4 = param_4;
    sprintf(buffer_48023,"[0x%02x][kernnel]");
    vsprintf(buffer_48023 + 0xf,param_1,&uStack_c);
    sVar1 = strlen(buffer_48023);
    if (999 < (int)sVar1) {
      sVar1 = 1000;
    }
    __memzero(local_40);
    local_2c = UdpWatchRemoteIP << 0x18 | (UdpWatchRemoteIP >> 8 & 0xff) << 0x10 |
               (UdpWatchRemoteIP >> 0x10 & 0xff) << 8 | UdpWatchRemoteIP >> 0x18;
    local_40[0] = 2;
    local_30 = 2;
    local_2e = 0x3930;
    local_3c = 0;
    if (UdpSock != 0) {
      SendUdpPacket(UdpSock,&local_30,0x10,buffer_48023,sVar1);
    }
  }
  return 0;
}



/* ============= FUNCTION: udp_del_media @ 00010370 ============= */


/* WARNING: Restarted to delay deadcode elimination for space: ram */

undefined4 udp_del_media(uint param_1,uint param_2)

{
  int iVar1;
  int iVar2;
  
  if (1 < param_1) {
    TRACE1("udp_del_media:Cid=%d ERR\r\n",param_1);
    return 0xffffffff;
  }
  TRACE1("udp_del_media:Cid=%d\r\n",param_1);
  if (param_2 < 2) {
    iVar2 = param_2 + param_1 * 2;
    TRACE1("udp_del_media:bMediaId=%d\r\n",param_2);
    TRACE1("udp_del_media:MediaSn=%d\r\n",iVar2);
    iVar1 = iVar2 * 0xf0;
    if (*(int *)(Medias + iVar1 + 0xa8) != 0) {
      *(undefined4 *)(Medias + iVar1 + 0xa8) = 0;
      if (*(int *)(Medias + iVar1 + 0xb0) == 2) {
        iV6Enable = iV6Enable + -1;
      }
      else {
        iV4Enable = iV4Enable + -1;
      }
    }
    iVar1 = iVar2 * 0xf0;
    mutex_lock(Medias + iVar1);
    if (*(int *)(Medias + iVar1 + 0x94) != 0) {
      sock_release();
      *(undefined4 *)(Medias + iVar1 + 0x94) = 0;
    }
    if (*(int *)(Medias + iVar2 * 0xf0 + 0x98) != 0) {
      sock_release();
      *(undefined4 *)(Medias + iVar2 * 0xf0 + 0x98) = 0;
    }
    if (*(int *)(Medias + iVar2 * 0xf0 + 0x90) != 0) {
      sock_release();
      *(undefined4 *)(Medias + iVar2 * 0xf0 + 0x90) = 0;
    }
    __memzero(iVar2 * 0xf0 + 0x1e63c,0x44);
    mutex_unlock(Medias + iVar1);
    TRACE1("udp_del_media:iV4Enable:%d iV6Enable:%d \n",iV4Enable,iV6Enable);
    return 0;
  }
  TRACE1("udp_del_media:bMediaId=%d ERR\r\n",param_2);
  return 0xffffffff;
}



/* ============= FUNCTION: udp_tx_data @ 00010504 ============= */


int udp_tx_data(uint param_1,uint param_2,int param_3,undefined4 param_4,undefined4 param_5)

{
  uint uVar1;
  short sVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  undefined1 *puVar6;
  
  uVar1 = 2 << (param_1 * 2 & 0xff);
  if (1 < param_1) {
    TRACE1("udp_tx_data:Cid=%d ERR\r\n",param_1);
    return -1;
  }
  if (1 < param_2) {
    TRACE1("udp_tx_data:bMediaId=%d ERR\r\n");
    return -1;
  }
  iVar4 = (param_1 * 2 + param_2 & 0xffff) * 0xf0;
  if (*(int *)(Medias + iVar4 + 0xa8) == 0) {
    return -1;
  }
  puVar6 = Medias + iVar4;
  if (param_3 == 0) {
    mutex_lock(puVar6);
    if (*(int *)(Medias + iVar4 + 0x94) == 0) goto LAB_00010638;
    sVar2 = SendUdpPacket(*(int *)(Medias + iVar4 + 0x94),*(undefined4 *)(Medias + iVar4 + 0x9c),
                          *(undefined4 *)(Medias + iVar4 + 0xa4),param_5,param_4);
    if (((uVar1 & TraceMask) == 0) || (iVar3 = *(int *)(Medias + iVar4 + 0x90), iVar3 == 0))
    goto LAB_00010630;
    iVar4 = iVar4 + 0x70;
  }
  else {
    mutex_lock(puVar6);
    if (*(int *)(Medias + iVar4 + 0x98) == 0) {
LAB_00010638:
      iVar5 = -99;
      goto LAB_000105d0;
    }
    sVar2 = SendUdpPacket(*(int *)(Medias + iVar4 + 0x98),*(undefined4 *)(Medias + iVar4 + 0xa0),
                          *(undefined4 *)(Medias + iVar4 + 0xa4),param_5,param_4);
    if (((uVar1 & TraceMask) == 0) || (iVar3 = *(int *)(Medias + iVar4 + 0x90), iVar3 == 0)) {
LAB_00010630:
      iVar5 = (int)sVar2;
      goto LAB_000105d0;
    }
    iVar4 = iVar4 + 0x80;
  }
  iVar5 = (int)sVar2;
  SendUdpPacket(iVar3,Medias + iVar4,0x10,param_5,param_4);
LAB_000105d0:
  mutex_unlock(puVar6);
  return iVar5;
}



/* ============= FUNCTION: udp_start @ 00010674 ============= */


undefined4 udp_start(undefined4 param_1,int param_2)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  
  if (Udp_Run != 1 && param_2 != 0) {
    iV4Enable = 0;
    iV6Enable = 0;
    Udp_Run = 1;
    fnUdpRecvCallback = param_2;
    __memzero(Medias,0x3c0);
    puVar1 = (undefined4 *)Medias;
    do {
      __mutex_init(puVar1,"&(Medias[i].lock)",&add_sn);
      puVar2 = puVar1 + 0x3c;
      puVar1[0x2a] = 0;
      puVar1 = puVar2;
    } while (puVar2 != &UdpWatchFlag);
    return 0;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: SetUdpWatch @ 00010704 ============= */


undefined4 SetUdpWatch(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int iVar1;
  
  if (param_1 == 1) {
    UdpWatchRemoteIP = param_2;
    if ((UdpSock == 0) && (iVar1 = sock_create_kern(2,2,0x11,&UdpSock,param_4), -1 < iVar1)) {
      UdpWatchFlag = 1;
    }
  }
  else {
    UdpWatchFlag = 0;
    if (UdpSock != 0) {
      sock_release();
      UdpSock = 0;
    }
  }
  return 0;
}



/* ============= FUNCTION: trace_add @ 00010788 ============= */


void trace_add(byte param_1,void *param_2,size_t param_3,undefined1 param_4,byte param_5)

{
  int iVar1;
  int iVar2;
  
  iVar2 = add_sn;
  if ((TraceMask & 2 - (uint)param_5 << (param_1 & 0xfe)) != 0) {
    iVar1 = TraceInSn * 0x408;
    *(short *)(TraceData + iVar1 + 2) = (short)param_3;
    TraceData[iVar1 + 1] = param_4;
    TraceData[iVar1] = param_1;
    *(int *)(TraceData + iVar1 + 4) = iVar2;
    memcpy(TraceData + iVar1 + 8,param_2,param_3);
    complete(ComTrace);
    TraceInSn = TraceInSn + 1;
    add_sn = add_sn + 1;
    if (TraceInSn == 0x32) {
      TraceInSn = 0;
    }
    return;
  }
  return;
}



/* ============= FUNCTION: dealudpdata @ 00010820 ============= */


undefined4 dealudpdata(short *param_1,int *param_2,int *param_3,int param_4)

{
  int iVar1;
  undefined1 *__s1;
  uint uVar2;
  
  __s1 = Medias + 0xb4;
  uVar2 = 0;
  do {
    if (*(int *)(__s1 + -4) == param_4) {
      if (param_4 == 1) {
        if ((*(int *)(__s1 + 0x20) == *param_3) && (*(int *)(__s1 + 0x24) == *param_2))
        goto LAB_000108a8;
      }
      else if ((param_4 == 2) &&
              ((iVar1 = memcmp(__s1,param_3,0x10), iVar1 == 0 &&
               (iVar1 = memcmp(__s1 + 0x10,param_2,0x10), iVar1 == 0)))) {
LAB_000108a8:
        if ((*(short *)(__s1 + 0x28) == param_1[1]) && (*(short *)(__s1 + 0x2c) == *param_1)) {
          if (fnUdpRecvCallback != (code *)0x0) {
            iVar1 = (((ushort)param_1[2] & 0xff) << 8 | (uint)((ushort)param_1[2] >> 8)) - 8;
            if (0x3ff < iVar1) {
              iVar1 = 0x400;
            }
            (*fnUdpRecvCallback)((int)uVar2 >> 1 & 0xffff,uVar2 & 1,0,(int)(short)iVar1,param_1 + 4)
            ;
            if (TraceRemoteIP != 0) {
              trace_add(uVar2 & 0xff,param_1 + 4,iVar1,0,1);
            }
          }
          return 0;
        }
        if ((*(short *)(__s1 + 0x2a) == param_1[1]) && (*(short *)(__s1 + 0x2e) == *param_1)) {
          if (fnUdpRecvCallback == (code *)0x0) {
            return 0;
          }
          iVar1 = (((ushort)param_1[2] & 0xff) << 8 | (uint)((ushort)param_1[2] >> 8)) - 8;
          if (0x3ff < iVar1) {
            iVar1 = 0x400;
          }
          (*fnUdpRecvCallback)((int)uVar2 >> 1 & 0xffff,uVar2 & 1,1,(int)(short)iVar1,param_1 + 4);
          if (TraceRemoteIP == 0) {
            return 0;
          }
          trace_add(uVar2 & 0xff,param_1 + 4,iVar1,1,1);
          return 0;
        }
      }
    }
    uVar2 = uVar2 + 1;
    __s1 = __s1 + 0xf0;
    if (uVar2 == 4) {
      return 1;
    }
  } while( true );
}



/* ============= FUNCTION: hook_func @ 00010a14 ============= */


undefined4 hook_func(undefined4 param_1,int param_2)

{
  undefined4 uVar1;
  int iVar2;
  
  if ((0 < iV4Enable) && (param_2 != 0)) {
    iVar2 = *(int *)(param_2 + 200) + (uint)*(ushort *)(param_2 + 0xa8);
    if ((iVar2 != 0) && (*(char *)(iVar2 + 9) == '\x11')) {
      uVar1 = dealudpdata(iVar2 + (*(byte *)(*(int *)(param_2 + 200) +
                                            (uint)*(ushort *)(param_2 + 0xa8)) & 0xf) * 4,
                          iVar2 + 0xc,iVar2 + 0x10,1);
      return uVar1;
    }
  }
  return 1;
}



/* ============= FUNCTION: hook_func6 @ 00010a70 ============= */


undefined4 hook_func6(undefined4 param_1,int param_2)

{
  char cVar1;
  int iVar2;
  undefined4 uVar3;
  char *pcVar4;
  int iVar5;
  
  if ((iV6Enable < 1) || (param_2 == 0)) {
    return 1;
  }
  iVar5 = *(int *)(param_2 + 200) + (uint)*(ushort *)(param_2 + 0xa8);
  if (iVar5 != 0) {
    cVar1 = *(char *)(iVar5 + 6);
    pcVar4 = (char *)(iVar5 + 0x28);
    while (iVar2 = ipv6_ext_hdr(cVar1), iVar2 != 0) {
      if (cVar1 == ';' || cVar1 == ',') {
        return 1;
      }
      if (cVar1 == '3') {
        iVar2 = ((byte)pcVar4[1] + 2) * 4;
      }
      else {
        iVar2 = ((byte)pcVar4[1] + 1) * 8;
      }
      cVar1 = *pcVar4;
      pcVar4 = pcVar4 + iVar2;
    }
    if (cVar1 == '\x11') {
      uVar3 = dealudpdata(pcVar4,iVar5 + 8,iVar5 + 0x18,2);
      return uVar3;
    }
  }
  return 1;
}



/* ============= FUNCTION: udp_close_all_socket @ 00010b14 ============= */


undefined4 udp_close_all_socket(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  
  puVar1 = (undefined4 *)Medias;
  do {
    puVar1[0x2a] = 0;
    mutex_lock(puVar1);
    if (puVar1[0x25] != 0) {
      sock_release();
      puVar1[0x25] = 0;
    }
    if (puVar1[0x26] != 0) {
      sock_release();
      puVar1[0x26] = 0;
    }
    if (puVar1[0x24] != 0) {
      sock_release();
      puVar1[0x24] = 0;
    }
    __memzero(puVar1 + 0x2b,0x44);
    puVar2 = puVar1 + 0x3c;
    mutex_unlock(puVar1);
    puVar1 = puVar2;
  } while (puVar2 != &UdpWatchFlag);
  return 0;
}



/* ============= FUNCTION: udp_close @ 00010b98 ============= */


undefined4 udp_close(void)

{
  fnUdpRecvCallback = 0;
  if (Udp_Run != 0) {
    Udp_Run = 0;
    iV4Enable = 0;
    iV6Enable = 0;
    udp_close_all_socket();
    return 0;
  }
  return 0xffffffff;
}



/* ============= FUNCTION: media_create_socket @ 00010bd8 ============= */


undefined4 media_create_socket(undefined4 *param_1,int param_2,undefined2 param_3)

{
  int iVar1;
  undefined2 local_34;
  undefined2 local_32;
  undefined4 local_30;
  undefined4 local_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  undefined4 uStack_20;
  
  local_32 = param_3;
  if (*(int *)(param_2 + 4) == 2) {
    __memzero(&local_34,0x1c);
    iVar1 = sock_create_kern(10,2,0x11,param_1);
    if (iVar1 < 0) goto LAB_00010d40;
    local_2c = *(undefined4 *)(param_2 + 8);
    local_34 = 10;
    uStack_28 = *(undefined4 *)(param_2 + 0xc);
    uStack_24 = *(undefined4 *)(param_2 + 0x10);
    uStack_20 = *(undefined4 *)(param_2 + 0x14);
    iVar1 = kernel_bind(*param_1,&local_34,0x1c);
    if (-1 < iVar1) goto LAB_00010c4c;
    TRACE1("udp_add_media_ko:bind socket err=%d\r\n");
    __memzero(&local_2c,0x10);
    iVar1 = kernel_bind(*param_1,&local_34,0x1c);
  }
  else {
    __memzero(&local_34,0x10);
    iVar1 = sock_create_kern(2,2,0x11,param_1);
    if (iVar1 < 0) {
LAB_00010d40:
      TRACE1("udp_add_media_ko:Create socket err=%d\r\n");
      return 0xffffffff;
    }
    local_30 = *(undefined4 *)(param_2 + 0x28);
    local_34 = 2;
    iVar1 = kernel_bind(*param_1,&local_34,0x10);
  }
  if (iVar1 < 0) {
    sock_release(*param_1);
    *param_1 = 0;
    TRACE1("udp_add_media_ko:bind socket err=%d\r\n",iVar1);
    return 0xffffffff;
  }
LAB_00010c4c:
  iVar1 = CSPKernel_QC_AppSet(*param_1,*(undefined4 *)(param_2 + 0x38),
                              *(undefined4 *)(param_2 + 0x3c),*(undefined4 *)(param_2 + 0x40));
  if (iVar1 != 0) {
    TRACE1("udp_add_media_ko:QC_AppSet socket err=%d\r\n");
    return 0;
  }
  return 0;
}



/* ============= FUNCTION: trace_create_v4socket @ 00010d50 ============= */


undefined4 trace_create_v4socket(undefined4 *param_1,uint param_2,uint param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined2 local_20;
  ushort local_1e;
  uint local_1c;
  
  __memzero(&local_20,0x10);
  iVar1 = sock_create_kern(2,2,0x11,param_1);
  if (iVar1 < 0) {
    TRACE1("udp_add_media_ko:Create trace socket err=%d\r\n");
    uVar2 = 0xffffffff;
  }
  else {
    local_1e = (ushort)((param_3 & 0xff) << 8) | (ushort)(param_3 >> 8) & 0xff;
    local_1c = param_2 << 0x18 | (param_2 >> 8 & 0xff) << 0x10 | (param_2 >> 0x10 & 0xff) << 8 |
               param_2 >> 0x18;
    local_20 = 2;
    iVar1 = kernel_bind(*param_1,&local_20,0x10);
    if (iVar1 < 0) {
      sock_release(*param_1);
      *param_1 = 0;
      TRACE1("udp_add_media_ko:bind trace socket err=%d\r\n",iVar1);
      uVar2 = 0xffffffff;
    }
    else {
      uVar2 = 0;
    }
  }
  return uVar2;
}



/* ============= FUNCTION: udp_add_media @ 00010e04 ============= */


undefined4 udp_add_media(uint param_1,uint param_2,void *param_3)

{
  undefined2 uVar1;
  uint uVar2;
  int iVar3;
  undefined4 uVar4;
  int iVar5;
  uint uVar6;
  uint uVar7;
  undefined1 *puVar8;
  undefined4 uVar9;
  uint uVar10;
  undefined1 *puVar11;
  undefined4 uVar12;
  int iVar13;
  
  TRACE1("udp_add_media:Cid=%d bMediaId=%d\r\n",param_1,param_2);
  if (1 < param_1 || (1 < param_2 || param_3 == (void *)0x0)) {
    return 0xffffffff;
  }
  iVar13 = param_2 + param_1 * 2;
  if (*(int *)((int)param_3 + 4) == 2) {
    TRACE1("udp_add_media: V6 L:%08X%08X%08X%08X:%d\r\n",*(undefined4 *)((int)param_3 + 8),
           *(undefined4 *)((int)param_3 + 0xc),*(undefined4 *)((int)param_3 + 0x10),
           *(undefined4 *)((int)param_3 + 0x14),*(undefined2 *)((int)param_3 + 0x30));
    TRACE1("udp_add_media: V6 R:%08X%08X%08X%08X:%d\r\n",*(undefined4 *)((int)param_3 + 0x18),
           *(undefined4 *)((int)param_3 + 0x1c),*(undefined4 *)((int)param_3 + 0x20),
           *(undefined4 *)((int)param_3 + 0x24),*(undefined2 *)((int)param_3 + 0x34));
    iVar5 = memcmp((void *)((int)param_3 + 8),zeroipv6,0x10);
    if (iVar5 == 0) {
      return 0xffffffff;
    }
    iVar5 = memcmp((void *)((int)param_3 + 0x18),zeroipv6,0x10);
    if (iVar5 == 0) {
      return 0xffffffff;
    }
    uVar10 = (uint)*(ushort *)((int)param_3 + 0x30);
    if (uVar10 == 0) {
      return 0xffffffff;
    }
    uVar7 = (uint)*(ushort *)((int)param_3 + 0x34);
    if (uVar7 == 0) {
      return 0xffffffff;
    }
  }
  else {
    TRACE1("udp_add_media: V4 L:%08X:%d\r\n",*(undefined4 *)((int)param_3 + 0x28),
           *(undefined2 *)((int)param_3 + 0x30));
    TRACE1("udp_add_media: V4 R:%08X:%d\r\n",*(undefined4 *)((int)param_3 + 0x2c),
           *(undefined2 *)((int)param_3 + 0x34));
    uVar6 = *(uint *)((int)param_3 + 0x28);
    if (uVar6 == 0) {
      return 0xffffffff;
    }
    uVar2 = *(uint *)((int)param_3 + 0x2c);
    if (uVar2 == 0) {
      return 0xffffffff;
    }
    uVar10 = (uint)*(ushort *)((int)param_3 + 0x30);
    if (uVar10 == 0) {
      return 0xffffffff;
    }
    uVar7 = (uint)*(ushort *)((int)param_3 + 0x34);
    if (uVar7 == 0) {
      return 0xffffffff;
    }
    *(uint *)((int)param_3 + 0x28) =
         uVar6 << 0x18 | (uVar6 >> 8 & 0xff) << 0x10 | (uVar6 >> 0x10 & 0xff) << 8 | uVar6 >> 0x18;
    *(uint *)((int)param_3 + 0x2c) =
         uVar2 << 0x18 | (uVar2 >> 8 & 0xff) << 0x10 | (uVar2 >> 0x10 & 0xff) << 8 | uVar2 >> 0x18;
  }
  *(ushort *)((int)param_3 + 0x30) = (ushort)((uVar10 & 0xff) << 8) | (ushort)(uVar10 >> 8);
  *(ushort *)((int)param_3 + 0x34) = (ushort)((uVar7 & 0xff) << 8) | (ushort)(uVar7 >> 8);
  *(ushort *)((int)param_3 + 0x36) =
       *(ushort *)((int)param_3 + 0x36) << 8 | *(ushort *)((int)param_3 + 0x36) >> 8;
  *(ushort *)((int)param_3 + 0x32) =
       *(ushort *)((int)param_3 + 0x32) << 8 | *(ushort *)((int)param_3 + 0x32) >> 8;
  TRACE1("udp_add_media:dscp=%d vlanprio=%d quene=%d\r\n",*(undefined4 *)((int)param_3 + 0x38),
         *(undefined4 *)((int)param_3 + 0x3c),*(undefined4 *)((int)param_3 + 0x40));
  iVar5 = iVar13 * 0xf0;
  if (*(int *)(Medias + iVar5 + 0xa8) != 0) {
    *(undefined4 *)(Medias + iVar5 + 0xa8) = 0;
    if (*(int *)(Medias + iVar5 + 0xb0) == 2) {
      iV6Enable = iV6Enable + -1;
    }
    else {
      iV4Enable = iV4Enable + -1;
    }
  }
  iVar5 = iVar13 * 0xf0;
  puVar8 = Medias + iVar5;
  mutex_lock(puVar8);
  if (*(int *)(Medias + iVar5 + 0x94) != 0) {
    sock_release();
    *(undefined4 *)(Medias + iVar5 + 0x94) = 0;
  }
  if (*(int *)(Medias + iVar13 * 0xf0 + 0x98) != 0) {
    sock_release();
    *(undefined4 *)(Medias + iVar13 * 0xf0 + 0x98) = 0;
  }
  if (*(int *)(Medias + iVar13 * 0xf0 + 0x90) != 0) {
    sock_release();
    *(undefined4 *)(Medias + iVar13 * 0xf0 + 0x90) = 0;
  }
  iVar5 = iVar13 * 0xf0;
  TRACE1("All Socket Closed\n");
  iVar3 = media_create_socket(iVar5 + 0x1e624,param_3,*(undefined2 *)((int)param_3 + 0x30));
  if (iVar3 == 0) {
    iVar3 = media_create_socket(iVar5 + 0x1e628,param_3,*(undefined2 *)((int)param_3 + 0x32));
    if (iVar3 != 0) {
      sock_release(*(undefined4 *)(Medias + iVar5 + 0x94));
      *(undefined4 *)(Medias + iVar5 + 0x94) = 0;
      mutex_unlock(puVar8);
      TRACE1("udp_add_media:create rtcp socket err\r\n");
      return 0xffffffff;
    }
    if (TraceRemoteIP != 0) {
      iVar3 = trace_create_v4socket
                        (iVar5 + 0x1e620,TraceLocalIP,
                         (*(ushort *)((int)param_3 + 0x30) << 8 |
                         *(ushort *)((int)param_3 + 0x30) >> 8) + 1000);
      uVar10 = TraceRemoteIP;
      if (iVar3 == 0) {
        *(undefined2 *)(Medias + iVar5 + 0x70) = 2;
      }
      else {
        TRACE1("udp_add_media:create Trace socket err\r\n");
        uVar10 = TraceRemoteIP;
        *(undefined2 *)(Medias + iVar5 + 0x70) = 2;
        *(undefined4 *)(Medias + iVar5 + 0x90) = 0;
      }
      iVar5 = iVar13 * 0xf0;
      uVar6 = iVar13 * 2 + 0xfa1;
      uVar7 = (iVar13 + 2000) * 2;
      uVar10 = uVar10 << 0x18 | (uVar10 >> 8 & 0xff) << 0x10 | (uVar10 >> 0x10 & 0xff) << 8 |
               uVar10 >> 0x18;
      *(uint *)(Medias + iVar5 + 0x74) = uVar10;
      *(uint *)(Medias + iVar5 + 0x84) = uVar10;
      *(ushort *)(Medias + iVar5 + 0x82) =
           (ushort)((uVar6 & 0xff) << 8) | (ushort)(uVar6 >> 8) & 0xff;
      *(ushort *)(Medias + iVar5 + 0x72) =
           (ushort)((uVar7 & 0xff) << 8) | (ushort)(uVar7 >> 8) & 0xff;
      *(undefined2 *)(Medias + iVar5 + 0x80) = 2;
    }
    iVar5 = iVar13 * 0xf0;
    memcpy(Medias + iVar5 + 0xac,param_3,0x44);
    if (*(int *)((int)param_3 + 4) == 2) {
      __memzero(iVar5 + 0x1e5c8,0x1c);
      __memzero(iVar5 + 0x1e5e4,0x1c);
      *(undefined2 *)(Medias + iVar5 + 0x38) = 10;
      *(undefined2 *)(Medias + iVar5 + 0x3a) = *(undefined2 *)((int)param_3 + 0x34);
      uVar4 = *(undefined4 *)((int)param_3 + 0x1c);
      uVar9 = *(undefined4 *)((int)param_3 + 0x20);
      uVar12 = *(undefined4 *)((int)param_3 + 0x24);
      *(undefined4 *)(Medias + iVar5 + 0x40) = *(undefined4 *)((int)param_3 + 0x18);
      *(undefined4 *)(Medias + iVar5 + 0x44) = uVar4;
      *(undefined4 *)(Medias + iVar5 + 0x48) = uVar9;
      *(undefined4 *)(Medias + iVar5 + 0x4c) = uVar12;
      *(undefined2 *)(Medias + iVar5 + 0x54) = 10;
      *(undefined2 *)(Medias + iVar5 + 0x56) = *(undefined2 *)((int)param_3 + 0x36);
      uVar12 = *(undefined4 *)((int)param_3 + 0x24);
      uVar4 = *(undefined4 *)((int)param_3 + 0x1c);
      uVar9 = *(undefined4 *)((int)param_3 + 0x20);
      *(undefined4 *)(Medias + iVar5 + 0x5c) = *(undefined4 *)((int)param_3 + 0x18);
      *(undefined4 *)(Medias + iVar5 + 0x60) = uVar4;
      *(undefined4 *)(Medias + iVar5 + 100) = uVar9;
      *(undefined4 *)(Medias + iVar5 + 0x68) = uVar12;
      *(int *)(Medias + iVar5 + 0x9c) = iVar5 + 0x1e5c8;
      *(undefined4 *)(Medias + iVar5 + 0xa4) = 0x1c;
      *(int *)(Medias + iVar5 + 0xa0) = iVar5 + 0x1e5e4;
      if (*(int *)(Medias + iVar5 + 0xa8) != 2) {
        iV6Enable = iV6Enable + 1;
      }
    }
    else {
      *(undefined2 *)(Medias + iVar5 + 0x18) = 2;
      *(undefined4 *)(Medias + iVar5 + 0x1c) = *(undefined4 *)((int)param_3 + 0x2c);
      uVar1 = *(undefined2 *)((int)param_3 + 0x34);
      *(undefined2 *)(Medias + iVar5 + 0x28) = 2;
      *(undefined2 *)(Medias + iVar5 + 0x1a) = uVar1;
      *(undefined4 *)(Medias + iVar5 + 0x2c) = *(undefined4 *)((int)param_3 + 0x2c);
      uVar1 = *(undefined2 *)((int)param_3 + 0x36);
      *(int *)(Medias + iVar5 + 0xa0) = iVar5 + 0x1e5b8;
      *(int *)(Medias + iVar5 + 0x9c) = iVar5 + 0x1e5a8;
      *(undefined2 *)(Medias + iVar5 + 0x2a) = uVar1;
      puVar11 = Medias + iVar5;
      if (*(int *)(Medias + iVar5 + 0xa8) != 2) {
        puVar11 = iV4Enable;
      }
      *(undefined4 *)(Medias + iVar5 + 0xa4) = 0x10;
      if (*(int *)(Medias + iVar5 + 0xa8) != 2) {
        iV4Enable = puVar11 + 1;
      }
    }
    mutex_unlock(puVar8);
    puVar8 = iV4Enable;
    iVar5 = iV6Enable;
    *(undefined4 *)(Medias + iVar13 * 0xf0 + 0xa8) = 2;
    TRACE1("udp_add_media:iV4Enable:%d iV6Enable:%d \n",puVar8,iVar5);
    TRACE1("udp_add_media:Media Add Success\n");
    uVar4 = 0;
  }
  else {
    mutex_unlock(puVar8);
    TRACE1("udp_add_media:create rtp socket err\r\n");
    uVar4 = 0xffffffff;
  }
  return uVar4;
}



/* ============= FUNCTION: init_module @ 000113a8 ============= */


undefined4 init_module(void)

{
  nf_register_hooks(voice_nfho,2);
  ComTrace._0_4_ = 0;
  __init_waitqueue_head(0x11bec,"&x->wait",&__key_8265);
  return 0;
}



/* ============= FUNCTION: cleanup_module @ 000113ec ============= */


void cleanup_module(void)

{
  nf_unregister_hooks(voice_nfho,2);
  if (Udp_Run == 0) {
    return;
  }
  udp_close();
  return;
}



/* ============= FUNCTION: vsprintf @ 00020000 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int vsprintf(char *__s,char *__format,__gnuc_va_list __arg)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: complete @ 00020004 ============= */


/* WARNING: Control flow encountered bad instruction data */

void complete(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kernel_bind @ 0002000c ============= */


/* WARNING: Control flow encountered bad instruction data */

void kernel_bind(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: nf_register_hooks @ 00020010 ============= */


/* WARNING: Control flow encountered bad instruction data */

void nf_register_hooks(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: memcpy @ 00020014 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memcpy(void *__dest,void *__src,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: wake_up_process @ 00020018 ============= */


/* WARNING: Control flow encountered bad instruction data */

void wake_up_process(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: nf_unregister_hooks @ 0002001c ============= */


/* WARNING: Control flow encountered bad instruction data */

void nf_unregister_hooks(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: mutex_lock @ 00020020 ============= */


/* WARNING: Control flow encountered bad instruction data */

void mutex_lock(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: ipv6_ext_hdr @ 00020024 ============= */


/* WARNING: Control flow encountered bad instruction data */

void ipv6_ext_hdr(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: memcmp @ 00020028 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int memcmp(void *__s1,void *__s2,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __mutex_init @ 0002002c ============= */


/* WARNING: Control flow encountered bad instruction data */

void __mutex_init(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __memzero @ 00020030 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __memzero(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: wait_for_completion @ 00020034 ============= */


/* WARNING: Control flow encountered bad instruction data */

void wait_for_completion(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: __init_waitqueue_head @ 00020038 ============= */


/* WARNING: Control flow encountered bad instruction data */

void __init_waitqueue_head(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kthread_create_on_node @ 0002003c ============= */


/* WARNING: Control flow encountered bad instruction data */

void kthread_create_on_node(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: sprintf @ 00020040 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int sprintf(char *__s,char *__format,...)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: mutex_unlock @ 00020044 ============= */


/* WARNING: Control flow encountered bad instruction data */

void mutex_unlock(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: sock_create_kern @ 00020048 ============= */


/* WARNING: Control flow encountered bad instruction data */

void sock_create_kern(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: sock_release @ 0002004c ============= */


/* WARNING: Control flow encountered bad instruction data */

void sock_release(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: CSPKernel_QC_AppSet @ 00020050 ============= */


/* WARNING: Control flow encountered bad instruction data */

void CSPKernel_QC_AppSet(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: strlen @ 00020054 ============= */


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

size_t strlen(char *__s)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: kernel_sendmsg @ 0002005c ============= */


/* WARNING: Control flow encountered bad instruction data */

void kernel_sendmsg(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



/* ============= FUNCTION: msleep @ 00020060 ============= */


/* WARNING: Control flow encountered bad instruction data */

void msleep(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



