#!/usr/bin/env python3
"""Generate kotrace_targets.h from ARG_SIGNATURES.json.

For each (module, function) in the signatures JSON, emit a C struct
entry that tells kotrace's runtime trace stub:
  - the symbol name to splice
  - which of r0..r3 should be treated as pointers (for safe deref)
  - how many bytes to copy_from_kernel_nofault for each pointer arg

The struct layout (must match kotrace.c):

    struct trace_target {
        const char *name;           // symbol name inside the .ko
        u8          arg_kind;       // bitmap: bit i = arg i is pointer
        u8          deref[4];       // deref size for each arg (only if pointer)
                                    // 0..32 -> exact bytes; cap at 64 in stub
        u8          n_args;         // 0..4 — useful args
        u8          marker;         // 1-char marker for legacy log (auto)
    };

Output file: tasks/00.01.eth-driver/kotrace/kotrace_targets.h

Filtering: a TARGET_FILTER set below restricts to modules we care about
for ethernet (skip dsp_dev, voip etc). Per-module filtering can also be
done at runtime via procfs.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
JSON_PATH = ROOT / "tasks/00.10.02.re-stock-kmods/findings/ARG_SIGNATURES.json"
OUT_PATH  = ROOT / "tasks/00.01.eth-driver/kotrace/kotrace_targets.h"

# Modules whose functions we DO want to trace.  Comment a row out to skip.
TARGET_MODULES = (
    "tm",
    "switch",
    "plat_zxylzb_9128S",
    "idmfdb",
    "zx_ponreg",
    # "shellproc",   # debug shell — not eth-relevant
    # "patch",       # cache erratum patcher — irrelevant
    # "kudp",        # VoIP RTP tracer — irrelevant
)

# Cap deref to keep ring entries bounded.
DEREF_CAP = 64


def emit(out, sigs):
    out.write("/* AUTO-GENERATED by tasks/00.10.02.re-stock-kmods/scripts/")
    out.write("generate_kotrace_targets.py\n")
    out.write(" * DO NOT EDIT BY HAND. Regenerate after touching ARG_SIGNATURES.json.\n")
    out.write(" *\n")
    out.write(" * One trace_target entry per stock function. Used by kotrace's\n")
    out.write(" * trace stub to know how to capture each call (scalar value vs\n")
    out.write(" * safe-deref'd pointer).\n")
    out.write(" */\n")
    out.write("#ifndef KOTRACE_TARGETS_H\n")
    out.write("#define KOTRACE_TARGETS_H\n\n")
    out.write("/* Cap deref size per arg — keeps ring entries bounded. */\n")
    out.write(f"#define KOTRACE_DEREF_CAP   {DEREF_CAP}\n\n")
    out.write("struct trace_target_v2 {\n")
    out.write("\tconst char *name;\n")
    out.write("\tu8 arg_kind;          /* bit i = arg i is pointer */\n")
    out.write("\tu8 deref[4];          /* per-arg deref size (capped to KOTRACE_DEREF_CAP) */\n")
    out.write("\tu8 n_args;            /* 0..4 useful args */\n")
    out.write("\tchar marker;          /* legacy 1-char log marker */\n")
    out.write("};\n\n")
    out.write("struct trace_module_v2 {\n")
    out.write("\tconst char                      *mod_name;\n")
    out.write("\tconst struct trace_target_v2    *targets;\n")
    out.write("\tunsigned int                     n_targets;\n")
    out.write("};\n\n")

    total = 0
    skipped = 0
    for mod in TARGET_MODULES:
        funcs = sigs.get(mod, {})
        if not funcs:
            out.write(f"/* module \"{mod}\" — not found in signatures JSON */\n\n")
            continue
        out.write(f"/* === {mod} ({len(funcs)} functions) === */\n")
        out.write(f"static const struct trace_target_v2 kt_{mod}_targets[] = {{\n")
        for fname, spec in sorted(funcs.items()):
            args = spec.get("args", [])
            if len(args) > 4:
                args = args[:4]
            arg_kind = 0
            derefs   = [0, 0, 0, 0]
            for i, a in enumerate(args):
                kind = a.get("kind", "unknown")
                if kind == "pointer":
                    arg_kind |= (1 << i)
                    derefs[i] = min(a.get("deref", 32), DEREF_CAP)
                elif kind == "scalar":
                    pass  # zero bit
                else:
                    # unknown -> treat as scalar (no deref) to be safe
                    pass
            n_args = len(args)
            # Marker char — derived from first letter of fn name. Not unique
            # across modules but only used for legacy log output, the real
            # identifier is the address (resolved at probe-time).
            marker = (fname[0].lower() if fname else '?')
            if not marker.isalnum():
                marker = '?'
            out.write(
                f"\t{{ \"{fname}\","
                f" 0x{arg_kind:02x},"
                f" {{{derefs[0]},{derefs[1]},{derefs[2]},{derefs[3]}}},"
                f" {n_args},"
                f" '{marker}' }},\n"
            )
            total += 1
        out.write("};\n")
        out.write(f"#define KT_{mod.upper()}_COUNT  "
                  f"(sizeof(kt_{mod}_targets)/sizeof(kt_{mod}_targets[0]))\n\n")

    # Master module table
    out.write("/* Master table — kotrace iterates this on module-load to splice probes. */\n")
    out.write("static const struct trace_module_v2 kt_modules[] = {\n")
    for mod in TARGET_MODULES:
        if mod in sigs:
            # Map our underscore-safe ident back to the actual .ko name.
            # Map our identifier-safe module key back to the actual .ko name
            # (some have hyphens, others underscores — see ext/kmodules_dump/).
            # NOTE: the .ko file on disk is "plat-zxylzb_9128S.ko" (hyphen),
            # but insmod translates '-' to '_' so the kernel sees
            # "plat_zxylzb_9128S". kt_modules' mod_name is compared
            # against mod->name in find_trace_module_v2() — so we use
            # the kernel-visible (underscore) form here.
            ko_name_map = {
                "plat_zxylzb_9128S": "plat_zxylzb_9128S.ko",
                "zx_ponreg":         "zx_ponreg.ko",
                "tm":                "tm.ko",
                "switch":            "switch.ko",
                "idmfdb":            "idmfdb.ko",
                "shellproc":         "shellproc.ko",
                "patch":             "patch.ko",
                "kudp":              "kudp.ko",
            }
            ko_name = ko_name_map.get(mod, mod + ".ko")
            out.write(f"\t{{ \"{ko_name}\", kt_{mod}_targets, KT_{mod.upper()}_COUNT }},\n")
    out.write("};\n")
    out.write("#define KT_NUM_MODULES  (sizeof(kt_modules)/sizeof(kt_modules[0]))\n\n")

    out.write(f"/* Total tracable functions: {total} */\n")
    out.write(f"/* Skipped (no signature recovered or not in TARGET_MODULES): {skipped} */\n")
    out.write("#endif /* KOTRACE_TARGETS_H */\n")
    return total


def main():
    sigs = json.loads(JSON_PATH.read_text())
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w") as f:
        total = emit(f, sigs)
    sz = OUT_PATH.stat().st_size
    print(f"Wrote {OUT_PATH}")
    print(f"  {total} target entries  ({sz:,} bytes)")


if __name__ == "__main__":
    main()
